insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-241', 'VLT', NULL, 'Estrattore Bonus VLT', '-', 'Media', 'Done', 'OT-800', 'Jira', 'IT', NULL, 'GM-DEV', 'Nuova', NULL, '2024-12-31', NULL, '2024-12-19', '2024-12-19', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-242', 'VLT', NULL, 'Realizzazione report sessioni di gioco VLT perimetro LVR ', '-', 'Media', 'Done', 'VLT-312', 'Jira', 'IT', NULL, 'Demand', 'live', NULL, '2024-12-31', NULL, '2024-12-31', '2024-12-31', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-243', 'VLT', NULL, 'Modifica layout cash call GSPA Romagna Giochi con IR', '-', 'Media', 'Done', 'VLT-343', 'Jira', 'BU', NULL, '-', 'Sviluppo e test conclusi
da to be planned a prod release', 'da rilasciare in prod insieme ad OTP', '2024-12-31', NULL, '2024-12-31', '2024-12-31', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-244', 'VLT', NULL, 'Integrazioni BPM', 'creazione vista esercizi per il concessionario GMT e per il concessionario LVR', 'Media', 'Done', 'OT-802', 'Jira', 'IT', NULL, 'IT', 'Live', NULL, '2024-12-31', NULL, '2025-01-08', '2025-01-08', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-245', 'VLT', NULL, 'Implementazione di un''interfaccia per la gestione ingegnerizzata delle omologhe (sia piattaforme che giochi)', '-', 'Media', 'Done', 'OT-686', 'Jira', 'IT', NULL, 'TCH', 'in test su LVR (ma ci sono le omologhe di entrambe le concessionarie)', '-', '2024-10-11', NULL, '2024-10-11', '2024-10-11', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-246', 'VLT', NULL, 'IMPLEMENTAZIONE BONUS SALE GAMENET_MENXLE _4_SOGLIE 3', '-', 'Media', 'Done', 'VLT-308', 'Jira', 'BU', NULL, 'BU', 'Live', NULL, '2024-07-25', NULL, '2024-07-25', '2024-07-25', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-247', 'VLT', NULL, 'Richiesta modifica Report Manutentore R421', '-', 'Media', 'Done', 'VLT-303', 'Jira', 'IT', NULL, 'GM-DEV', 'Finito ma in corso analisi su richiesta', NULL, '2024-07-12', NULL, '2024-07-12', '2024-07-12', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-248', 'VLT', NULL, 'EC Annuale GMNT', '-', 'Media', 'Done', 'VLT-233', 'Jira', 'BU', NULL, 'BU', 'LIVE', 'pubblicazione rendiconto in attesa di IR e di Extra aggio', '2024-06-12', NULL, '2024-06-12', '2024-06-12', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-249', 'VLT', NULL, 'IMPLEMENTAZIONE BONUS SALE GAMENET', '-', 'Media', 'Done', 'VLT-285', 'Jira', 'IT', NULL, 'TCH', 'Live', '-', '2024-06-10', NULL, '2024-06-10', '2024-06-10', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-250', 'VLT', NULL, 'IMPLEMENTAZIONE BONUS SALE GAMENET', '-', 'Media', 'Done', 'VLT-295', 'Jira', 'IT', NULL, 'TCH', 'Live', '-', '2024-06-20', NULL, '2024-06-20', '2024-06-20', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-251', 'VLT', NULL, 'Report Anagrafico Dati Macchine - Parco Macchine VLT - CR1', '-', 'Media', 'Done', 'VLT-232', 'Jira', 'BU', NULL, 'BU', 'Live', '-', '2024-05-09', NULL, '2024-05-09', '2024-05-09', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-252', 'VLT', NULL, 'Spostamento VIP Chair (20102003066) dalla sala Magic slot Fortuna', '-', 'Media', 'Done', 'VLT-190', 'Jira', 'BU', NULL, 'ADI ', 'individuata soluzione per trattare debitamente la raccolta nella sala precedente
Macchina inserita nel cumulo delle rettifiche il giorno 05/04', 'Avviare sviluppi su w1 Aprile', '2024-07-10', NULL, '2024-07-10', '2024-07-10', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-253', 'VLT', NULL, 'DASHBOARD VCG_Implementazione informazioni mail automatica', '-', 'Media', 'Done', 'VLT-245', 'Jira', 'IT', NULL, 'ADI', 'Mandata in test a Silvia in data 22/03', NULL, '2024-03-22', NULL, '2024-03-22', '2024-03-22', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-254', 'VLT', '{"LGP"}', 'Tkt Manutentori', 'Possibilità di inserimento Rapportino su LGP', 'Media', 'Done', 'BSS-710', 'Jira', 'IT', 'Lorenzo Bontempi', 'TIBCO', 'LGP - sviluppi e collaudo chiusi', 'Valutare se scorporabile dal pacchetto Zen', '2026-04-16', '2026-06-09', NULL, NULL, '2026 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-255', 'VLT', NULL, 'Re-Import Storico per tuning campo GGY (rend) LVR ', '-', 'Media', 'Done', 'VLT-229', 'Jira', 'IT', NULL, 'ADI ', 'Chiuso import e rilasciata in test ad Ivano in data 01/03
Live, approvata da committenza in data 07/03', NULL, '2024-09-05', NULL, '2024-09-05', '2024-09-05', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-256', 'VLT', NULL, 'IMPLEMENTAZIONE BONUS SALE GAMENET_MENXLE _2_SOGLIE 1', '-', 'Media', 'Done', 'VLT-298', 'Jira', 'BU', NULL, 'BU', 'Censito', '-', '2024-07-01', NULL, '2024-07-01', '2024-07-01', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-257', 'VLT', NULL, 'Regole manutenzione vlt_Romagna', '-', 'Media', 'Done', 'VLT-325', 'Jira', 'IT', NULL, 'IT', 'LIVE', '-', '2024-10-03', NULL, '2024-10-03', '2024-10-03', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-258', 'VLT', NULL, 'Associazione AVP4 (commessa GMT) al fornitore SACI', '-', 'Media', 'Done', 'VLT-322', 'Jira', 'IT', NULL, 'ADI', 'Da dev a last Done', 'vedi VLT-325', '2024-10-01', NULL, '2024-10-01', '2024-10-01', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-259', 'VLT', NULL, 'SeGag', 'BONUS MENXLI - INSERIMENTO DUE NUOVI BONUS A XSTEMA', 'Media', 'Done', 'VLT-226', 'Jira', 'IT', NULL, 'ADI', 'Live', '', '2024-03-04', NULL, '2024-03-04', '2024-03-04', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-260', 'VLT', NULL, 'Cruscotto VLT', 'Dashboard Automatismo per preparazione nuove macchine Spielo ', 'Media', 'Done', 'VLT-299', 'Jira', 'BU', NULL, 'GM-DEV', 'Live', NULL, '2024-07-31', NULL, '2024-07-31', '2024-07-31', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-261', 'VLT', NULL, 'Cruscotto VLT', 'Dashboard VGC_Implementazione categoria attività (cessazione sale con annessi apparati)', 'Media', 'Done', 'VLT-241', 'Jira', 'BU', NULL, 'GM-DEV', 'implementata e testata su GMT
implementata su LVR
da UAT a LAST DONE', 'Verifica in prod', '2024-07-31', NULL, '2024-07-31', '2024-07-31', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-262', 'VLT', NULL, 'IGM BONUS', 'IMPLEMENTAZIONE SU SEGAG DI 2 NUOVE TIPOLOGIE DI BONUS MENXLI A 3 SOGLIE', 'Media', 'Done', 'VLT-256', 'Jira', 'BU', NULL, 'TCH', 'Live', NULL, '2024-05-07', NULL, '2024-05-07', '2024-05-07', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-263', 'VLT', NULL, 'MGM', 'Revisione corretto calcolo spettanze su Rettifiche VLT ', 'Media', 'Done', 'VLT-469', 'Jira', 'IT', 'Lorenzo Bontempi', 'IT', NULL, NULL, '2025-08-29', NULL, '2025-08-21', '2025-08-21', '2025 Q3', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-264', 'VLT', NULL, 'Cambio aliquota contratto Inspired concessionario GMT ', '-', 'Media', 'Done', 'VLT-493', 'Jira', 'BU', 'Manuela Graziani', 'IT', 'jira postumo ad attività svolta', NULL, '2025-09-26', NULL, '2025-09-26', '2025-09-26', '2025 Q3', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-265', 'VLT', NULL, 'LVR - Ares', 'Introduzione piattaforma', 'Media', 'Done', NULL, 'Manuale', 'IT', NULL, 'ADI + BU', '
Hw predisposto; Rete ok; Test in Sala Test ok
Integrazione Vs SAP ok
Ultima release di piattaforma certificata (include la nuova messaggistica)
Certificazione per il collaudo ottenuta 01/02, macchine abilitate al gioco il 05/02, attualmente sono presenti 5 giochi
', NULL, '2024-02-05', NULL, '2024-02-05', '2024-02-05', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-266', 'VLT', NULL, 'Comunicazioni Consegne e Ritiri Logistica VLT', 'Invio automatico mail su ticket Gaming a tutti gli attori coinvolti (Trasportatore-GdS-Gestore/Manutentore-Sales)', 'Media', 'Done', 'CCLO-290', 'Jira', 'BU', NULL, 'SAPCRM+ Demand', 'Live', NULL, '2024-09-12', '2024-09-12', '2024-09-12', '2024-09-12', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-267', 'VLT', NULL, 'Cruscotto VLT', 'MODIFICHE CRUSCOTTO DIREZIONALE VLT - REPORT R39', 'Media', 'Done', 'VLT-260', 'Jira', 'IT', NULL, 'ADI', 'Live il giorno 16/04', NULL, '2024-04-16', NULL, '2024-04-16', '2024-04-16', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-268', 'VLT', NULL, 'Cruscotto VLT', 'Modifiche processi Sikuli GMT-LVR per NOVOMATIC', 'Media', 'Done', 'VLT-275', 'Jira', 'IT', NULL, 'ADI', 'Live', NULL, '2024-07-25', NULL, '2024-07-25', '2024-07-25', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-269', 'VLT', NULL, 'Modello Unico Anagrafico', 'Parco Macchine VLT', 'Media', 'Done', 'VLT-53', 'Jira', 'BU', NULL, 'BU', 'Live', '-', '2024-05-09', NULL, '2024-05-09', '2024-05-09', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-270', 'VLT', NULL, 'LVR', 'Portale LGP Inserimento nota per recupero rendiconti pre 2023', 'Media', 'Done', 'VLT-198', 'Jira', 'IT', NULL, NULL, 'inserito item a MP', 'Verifiche lato committenza', '2024-02-06', NULL, '2024-02-06', '2024-02-06', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-271', 'VLT', NULL, 'Motore Bonus VLT', 'Procedura popolamento tabelle da file excel', 'Media', 'Done', 'OT-680', 'Jira', 'IT', NULL, 'Demand', 'da test a last done', 'comunicare alla BU le logiche di produzione del file', '2024-11-28', NULL, '2024-11-28', '2024-11-28', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-272', 'VLT', NULL, 'LGP', 'Sezione manutentori - regole di assegnazione "Romagna"', 'Media', 'Done', 'VLT-213', 'Jira', 'IT', NULL, 'IT', 'Live su LGP
Modificato il Report sul Cruscotto (Recchia/Conti)', '-', '2024-03-08', NULL, '2024-03-08', '2024-03-08', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-273', 'VLT', NULL, 'Modello DWH VLT - budget', 'Dashboard interne PBI', 'Media', 'Done', 'REP-379', 'Jira', 'BU', NULL, 'BU', 'effettuata ultima modifica necessaria e rilasciato in verifica
- chiesto FB a Falcone in data 07/11
- In attesa FB da Arianna
- chiesta autorizzazione a SOC per ambiente di sviluppo
SOC ha risposto, in attesa lavorazione CMFP-113332', NULL, '2025-10-24', '2025-11-26', '2025-11-26', '2025-11-26', '2025 Q4', false, 'In ritardo per tempi lunghi di security', '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-274', 'VLT', NULL, 'MGM - Nuovo Portale Contratti GM', 'Sezione rettifiche VLT-Variazione contabile e totale inserito', 'Media', 'Done', 'OT-401', 'Jira', 'IT', NULL, 'GM-Dev', 'Live', NULL, '2024-08-30', NULL, '2024-08-30', '2024-08-30', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-275', 'VLT', NULL, 'LGP', 'Ticket Manutentori - Aggiunta info di anagrafica', 'Media', 'Done', 'VLT-160', 'Jira', 'IT', NULL, NULL, 'Creata issue su JIRA', 'Verifiche lato committenza
Da rilasciare assieme a GeoMapper', '2024-02-06', NULL, '2024-02-06', '2024-02-06', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-276', 'VLT', NULL, 'Motore Bonus VLT', 'Workround previsioni Bonus VLT', 'Media', 'Done', 'OT-724', 'Jira', 'IT', NULL, 'GM-DEV', 'test sospesi per portale contratti
chiusi test da test a last done', '-', '2024-10-29', NULL, '2024-10-29', '2024-10-29', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-277', 'AWP', '{"LGP"}', 'Info legenda stati ticket', 'Nel portale LGP sia lato GMT che LVR, nella sezione “dashboard riepilogativa” dei ticket, si richiede di inserire la seguente frase nello spazio disponibile tra i tasti Annulla - Ricerca e la Legenda:
Dopo l’inoltro di un ticket, cliccando l’icona presente nella colonna “cronologia del ticket” sarà possibile consultare in tempo reale tutte le interazioni avvenute con l’ufficio Assistenza Gaming AWP.', 'Bassa', 'To Do', 'AWP-2886', 'Jira', 'BU', NULL, 'GP', NULL, NULL, '2026-09-30', NULL, NULL, NULL, '2026 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-278', 'AWP', NULL, 'MGM', 'Richiesta inserimento sulla rivalsa GMT e LVR della colonna del produttore schede', 'Bassa', 'Done', 'AWP-2557', 'Jira', 'IT', 'Lorenzo Bontempi, Manuela Graziani', 'IT', 'Go-live 17/02', NULL, '2026-03-31', '2026-02-20', '2026-02-17', '2026-02-17', '2026 Q1', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-279', 'AWP', NULL, 'Ricerca e download rendiconti AWP su MGM', '-', 'Bassa', 'Done', 'AWP-2477', 'Jira', 'IT', 'Lorenzo Bontempi', 'IT', 'Censita di recente
in sviluppo', NULL, '2026-03-31', '2026-02-17', '2026-02-17', '2026-02-17', '2026 Q1', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-280', 'AWP', NULL, 'Procedura di cancellazione completa del calcolo della quindicina', '-', 'Bassa', 'Done', 'OT-886', 'Jira', 'IT', 'Nello', 'GM-DEV', 'Finiti gli sviluppi', 'in attesa ricopertura ambiente di collaudo LVR per effettuare il test;
eventualmente si effettuerà il test in prod', '2025-03-31', '2025-06-30', '2025-05-13', '2025-05-13', '2025 Q2', false, 'Gli sviluppi erano stati effettuati in tempo, ciò che ha provocato il ritardo è l''ambiente di collaudo', '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-281', 'AWP', NULL, 'Cruscotto Network Support', 'Nuovo cruscotto per la gestione operativa del gruppo', 'Bassa', 'Cancelled', NULL, 'Manuale', 'BU', 'Lorenzo Bontempi, Manuela Graziani', 'Demand', 'effettuata prima call con BU', 'La richiesta presuppone una riorganizzazione del modello dati verso una vista cross concessionario, tale attività costituisce di per sé una progettualità a se stante utile non solo alla richiesta attuale e da lavorare a parte. => attività sospesa fino a disegno della soluzione.', NULL, NULL, NULL, NULL, 'TBD', false, NULL, '61-100', '50+') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-282', 'AWP', '{"GAP"}', 'Ottimizzazione - Cruscotto GAP', 'Integrazione delle attuali procedure in php per il caricamento su cruscotto GAP dei file della bimestrale ADM', 'Bassa', 'To Do', 'AWP-2660', 'Jira', 'IT', 'Nello', 'IT', NULL, 'Iniziare analisi in Q2', '2026-09-30', NULL, NULL, NULL, '2026 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-283', 'AWP', NULL, 'Spettanze: Modifica gestione ricalcolo manuale e rilancio procedura (funzionalità condizionate)', '-', 'Bassa', 'Done', 'OT-887', 'Jira', 'IT', 'Nello', 'GM-DEV', 'in corso sviluppi (annuali chiusi)', '-', '2025-03-31', '2025-04-09', '2025-04-09', '2025-04-09', '2025 Q2', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-284', 'AWP', NULL, 'AWP - SEGAG Ingegnerizzazione invio comunicazioni peo - lato Gmt - LVR ', 'Creazione modelli precompilati', 'Bassa', 'Cancelled', 'OT-792', 'Jira', 'IT', 'Manuela Graziani', 'ADI', 'Riassorbita in altre richieste', NULL, '2025-04-09', NULL, NULL, NULL, '2025 Q2', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-285', 'AWP', NULL, 'Analisi e fixing chiavi primarie base dati GAP – Calcolo Spettanze', '-', 'Bassa', 'Done', 'OT-885', 'Jira', 'IT', 'Nello', 'GM-DEV', 'Live', NULL, '2025-03-17', NULL, '2025-03-13', '2025-03-13', '2025 Q1', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-286', 'AWP', NULL, 'SEGAG - Gestione Noe digitalizzati', 'Modifica richiesta DUPLICATO ', 'Bassa', 'Done', 'AWP-1873', 'Jira', 'IT', 'Manuela Graziani', 'GM-DEV', 'Censito', 'inizio post lavorazione PEC', '2025-04-15', NULL, '2025-04-07', '2025-04-07', '2025 Q2', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-287', 'AWP', NULL, 'Cruscotto AWP', 'CREAZIONE REPORT TIR TIPO CONTRATTI ', 'Bassa', 'Done', 'AWP-1439', 'Jira', 'IT', NULL, 'ADI', 'mandato in Dev in data 19/09, possibile rilascio in settimana prossima', '-', '2024-12-31', NULL, '2025-01-21', '2025-01-21', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-288', 'AWP', NULL, 'Cruscotto AWP', 'Report | Inserimento operatore tecnico per i TIR', 'Bassa', 'Done', 'AWP-1693', 'Jira', 'IT', NULL, 'Committenza', 'messa in done in data 06/02', 'chiudere test', '2024-12-31', NULL, '2025-02-06', '2025-02-06', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
