insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-001', 'AWP', '{"GAP"}', 'GAP', 'Integrazione storico rendiconti LVR (2018-2022)', 'Alta', 'Done', 'OT-935', 'Jira', 'IT', 'Nello', 'GM-DEV', 'Attività ad altra priorità data la chiusura VDI-IGT
15/04 attività sospesa per estrazione previsionale bonus VLT; shift di due giorni', 'sviluppo
rilascio per il 5 maggio', '2025-04-30', '2025-05-05', '2025-05-05', '2025-05-05', '2025 Q2', false, 'shift necessario per estrazione previsionale bonus annuale vlt', '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-002', 'AWP', '{"GAP"}', 'GAP', 'Integrazione storico rendiconti LVR (pre-2018)', 'Alta', 'Cancelled', 'OT-994', 'Jira', 'IT', 'Nello', 'Demand', 'Attività necessaria in previsione della dismissione di macchina IGT
mandata mail a marco mezzabarba
impossibile accedere, vedere email per il 9
necessario comunque passaggio con IGT
Ricevuta risposta da SYS per accesso cartella; verificata presenza file dal 2010 al 2014, tutti gli annuali ma mancanza anni 2015-17', 'Capire dove reperire i 3 anni mancanti (necessario IGT)', '2025-09-30', NULL, NULL, NULL, '2025 Q3', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-003', 'AWP', '{"MGM"}', 'Sviluppo del Tool Network Support', 'Tool a supporto della BU (focus on Commerciali) e clienti, che permetta analisi e monitoraggi pi efficaci, recepire informazioni strutturate dal territorio e pianificare e monitorare meglio le attività sul territorio', 'Alta', 'Dev', 'AWP-2692', 'Jira', 'BU', 'Lorenzo Bontempi, Manuela Graziani', 'IT', 'Creato il Jira e caricati i requisiti consolidati in data 30/03.
Avviate analisi e stima da 2^ settimana Maggio
Analisi/sviluppo lato DB chiuso', 'Avviare lavorazione lato FE', '2026-06-30', '2026-09-30', NULL, NULL, '2026 Q3', false, NULL, '61-100', '50+') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-004', 'AWP', '{"Cruscotto AWP"}', 'Cruscotto AWP', 'AWP anomale GMT e LVR ', 'Alta', 'Done', 'AWP-1272', 'Jira', 'IT', 'Manuela Graziani', 'ADI', 'rimessa in test il giorno 05/03', '-', '2024-12-31', '2025-06-30', '2025-05-19', '2025-05-19', '2025 Q2', false, 'Attività composita soggetta a più rilavorazioni successive', '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-005', 'AWP', '{"Cruscotto AWP"}', 'Cruscotto AWP', 'Cruscotto Direzionale | Report A019_ sia lato GMT che LVR', 'Alta', 'Done', 'AWP-1975', 'Jira', 'IT', 'Manuela Graziani', 'ADI', 'in attesa di ok da parte della committenza (LVR)', NULL, '2025-09-30', NULL, '2025-08-22', '2025-08-22', '2025 Q3', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-006', 'AWP', '{"Cruscotto AWP"}', 'Cruscotto AWP', 'Report A100 - Interrogazione massiva AWP (GMT/LVR)', 'Alta', 'Done', 'AWP-1360', 'Jira', 'IT', NULL, 'ADI', 'Live', '-', '2024-12-31', NULL, '2024-12-19', '2024-12-19', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-007', 'AWP', '{"Cruscotto AWP"}', 'Cruscotto AWP', 'Report RR26 sia lato GMT che LVR', 'Alta', 'Done', 'AWP-1481', 'Jira', 'IT', NULL, 'ADI', 'live', '-', '2024-12-31', NULL, '2025-01-17', '2025-01-17', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-008', 'AWP', NULL, 'Digitalizzazione NOE', 'Modifiche per gestire nuovi tracciati per area riservata AdM per richiesta NOE', 'Alta', 'Done', 'OT-846', 'Jira', 'IT', NULL, 'ADI', 'Fatto primo passaggio con AdM (max 100 NOE per le richieste massive)
Richiesti esempi file sia per richiesta che per output
Anomalie lato SOGEI corrette, generazione corretta del file possibile
da definition a last done', 'Capire come indirizzare i necessari sviluppi
in attesa delle firme da parte dei responsabili
Necessario capire in che modo il file viene restituito', '2024-12-31', NULL, '2024-12-19', '2024-12-19', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-009', 'AWP', NULL, 'AWP - SEGAG -  Ingegnerizzazione invio comunicazioni PEC - lato Gmt - LVR ', 'Integrazione ricezione ricevute con funzionalità già presente sul robottino', 'Alta', 'Done', 'OT-790', 'Jira', 'IT', 'Manuela Graziani', 'ADI', 'LIVE', 'in attesa utenza del nuovo indirizzo PEC LVR e conseguente rilavorazione 
da affrontare tema dell''eliminazione', '2025-01-31', '2025-03-07', '2025-03-18', '2025-03-18', '2025 Q1', false, 'problematiche di esercizio e attività sul portale contratti, problemi di rete per apertura porta', '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-010', 'AWP', NULL, 'Digitalizzazione NOE', 'inserimento qr code portale GMT e LVR', 'Alta', 'Done', 'AWP-1662', 'Jira', 'IT', 'Lorenzo Bontempi', 'GM-DEV + ADI', 'concluso in data 10/02', NULL, '2025-02-05', NULL, '2025-02-10', '2025-02-10', '2025 Q1', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-011', 'AWP', NULL, 'PDA', 'Aggiornamento parametri polling (da 1 a 25 min)', 'Alta', 'Done', 'OT-399', 'Jira', 'IT', NULL, 'IT', 'LIVE', NULL, '2024-06-11', NULL, '2024-06-11', '2024-06-11', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-012', 'AWP', NULL, 'Cruscotto AWP', 'Automatismo PDA - implementare un sistema che permette all utente di effettuare la funzione ping telnet e riavvio di un pda', 'Alta', 'Done', 'AWP-397', 'Jira', 'IT', NULL, '-', 'Feedback ricevuto, LIVE', NULL, '2024-01-20', NULL, '2024-02-13', '2024-02-13', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-013', 'AWP', NULL, 'LGP', 'Caricamento massivo backoffice DB dati PDV per Mappatura', 'Alta', 'Done', 'OT-512', 'Jira', 'IT', NULL, 'IT', NULL, NULL, '2024-05-14', NULL, '2024-05-14', '2024-05-14', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-014', 'AWP', '{"LGP"}', 'Nuova GUI Lettura AWP', 'Introduzione di una nuova GUI sul portale LGP per l''assistenza tecnica, con l’obiettivo di rendere più efficiente e autonoma la gestione delle operazioni sulle AWP in esercizio, riducendo la necessità di contatto con l’Assistenza Gaming AWP', 'Alta', 'Definition', 'AWP-2885', 'Jira', 'BU', 'Lorenzo Bontempi', 'IT', 'Creato Jira in data 13/07', 'In corso analisi e definizione del requisito con la committenza', '2026-11-30', NULL, NULL, NULL, '2026 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-015', 'AWP', NULL, 'GAP', 'Conto Giudiziale', 'Alta', 'Done', 'OT-394', 'Jira', 'IT', NULL, 'GM-DEV + ADI', 'Verifiche ADI GMNT chiuse; dati GMNT inviati
Chiuse verifiche LVR ed invio dati entro 27/2', NULL, '2024-02-27', NULL, '2024-02-27', '2024-02-27', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-016', 'AWP', NULL, 'BPM', 'Fase 1', 'Alta', 'Done', NULL, 'Manuale', 'BU', NULL, 'IT - Kofax', 'Prima fase di analisi chiusa per quasi tutti i processi ma siamo in importante rilavorazione poiché molti dei processi disegnati non sono stabili e necessitano di redesign lato BU. Ove possibile è iniziata anche l’analisi di dettaglio IT e relativa progettazione.', 'Analisi congiunta in corso
Previsti rilasci incrementali', '2024-02-27', NULL, '2024-02-27', '2024-02-27', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-017', 'AWP', NULL, 'LGP GMT/LVR', 'Funzionalità TIR - Richiesta NOE AWP Concessionario', 'Alta', 'Done', 'AWP-572', 'Jira', 'IT', NULL, 'Demand + BU', 'Ricevuto ok per il rilascio
Esercenti TIR NON devono poter perfezionare la richiesta
Test in prod con 6 NOE effettuato', '-', '2024-01-20', NULL, '2024-01-26', '2024-01-26', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-018', 'AWP', NULL, 'Portale LGP', 'Implementazione dati forfettario su LGP', 'Alta', 'Done', 'AWP-639', 'Jira', 'IT', NULL, 'BU', 'Sviluppi conclusi
Chiuso fine tuning sul codice
incontro organizzato:
Stabilita la soluzione
Ricevuto ok da BU (Marcolini) in data 06/02/2024, modificato lo stato in Done su Jira
LIVE', NULL, '2023-12-30', NULL, '2024-02-06', '2024-02-06', '2023 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-019', 'AWP', NULL, 'MGM - Nuovo Portale Contratti GM', 'Implementazione funzione di impostazione della quota del Concessionario', 'Alta', 'Done', 'OT-237', 'Jira', 'IT', NULL, 'GM-DEV + BU', 'LIVE', '-', '2023-12-30', NULL, '2024-06-11', '2024-06-11', '2023 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-020', 'AWP', NULL, '25^ rendiconto LVR (2023)', 'Maschera su LGP', 'Alta', 'Cancelled', 'LGP-89', 'Jira', 'Amm.e', NULL, '- ', 'Incontro organizzato:
- al vaglio con Sistemi la possibile soluzione trovata
La soluzione individuata non richiede lavorazioni su LGP', '- ', '2024-02-12', NULL, NULL, NULL, '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-021', 'AWP', NULL, 'GAP', 'Modifiche per 25^ LVR e Fornitura annuale 2023 per AdE ', 'Alta', 'Done', 'OT-259', 'Jira', 'IT', NULL, 'GM-Dev', 'Rilasciato in produzione
Chiusi i test in ambiente di Prod', 'Implementare EC G NoScass
In attesa data apertura dal BU', '2024-05-13', NULL, '2024-05-13', '2024-05-13', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-022', 'AWP', NULL, 'Cruscotto AWP', 'Report A105 RICERCA PDA PER VERIFICA FUNZIONALITA'' DI BASE ', 'Alta', 'Done', 'AWP-961', 'Jira', 'IT', NULL, 'ADI', 'Pronto, mandata in test in data 15/03
Live dal giorno 18/03', '- ', '2024-03-18', NULL, '2024-03-18', '2024-03-18', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-023', 'AWP', NULL, 'Cruscotto AWP', 'Report AA13 - Storico Messaggi 
Eliminazione del tasto "salva" nella sezione "elenco dei messaggi 480 in lavorazione"', 'Alta', 'Done', 'AWP-646', 'Jira', 'IT', NULL, 'ADI', 'Ricevuto feedback, LIVE', 'In attesa feedback', '2024-02-13', NULL, '2024-02-13', '2024-02-13', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-024', 'AWP', NULL, 'Cruscotto "Report A019 - Report blocchi slot" - sezione storico', 'Report analitico di tutti i blocchi e sblocchi avvenuti nel range selezionato, comprensivo di tutte le tipologie', 'Alta', 'Done', 'AWP-680', 'Jira', 'IT', NULL, '-', 'Lavorazione compleata in data 11/03, in test a pasquale
Test completati il giorno 18/03 --> far vedere a IT dev 25/03', '- ', '2024-03-18', NULL, '2024-03-18', '2024-03-18', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-025', 'AWP', NULL, 'Cruscotto AWP', 'Report r029 - Elenco operazioni su LGP ', 'Alta', 'Done', 'AWP-288', 'Jira', 'IT', NULL, 'ADI - AWP-Dev', 'LIVE il giorno 08/04', NULL, '2024-04-08', NULL, '2024-04-08', '2024-04-08', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-026', 'AWP', NULL, 'Gestionale Magazzino AWP Dirette', 'SAM', 'Alta', 'Done', 'AWP-13', 'Jira', 'BU', NULL, 'IT - Neptune', 'Live', NULL, '2024-01-20', NULL, '2024-06-15', '2024-06-15', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-027', 'AWP', NULL, 'MGM - Nuovo Portale Contratti GM', 'Sezione rettifiche spettanza Concessionaria', 'Alta', 'Done', 'OT-238', 'Jira', 'IT', NULL, 'AWP-Dev', 'Live il giorno 14/03', NULL, '2024-03-14', NULL, '2024-03-14', '2024-03-14', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-028', 'AWP', NULL, 'Cruscotto AWP', 'Storico Report R0218 - Elenco delle AWP con inaccessibilità lato GMNT e LVR', 'Alta', 'Done', 'AWP-721', 'Jira', 'IT', NULL, '- ', 'LIVE il giorno 08/04', '- ', '2024-03-20', NULL, '2024-04-08', '2024-04-08', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-029', 'AWP', NULL, 'GAP', 'Tool caricamento file bimestre', 'Alta', 'Done', 'OT-256', 'Jira', 'IT', NULL, 'GM-DEV + ADI', 'Live', 'Implementare il tool per il caricamento dei bimestri precedenti sia GMNT che LVR', '2024-05-13', NULL, '2024-05-13', '2024-05-13', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-030', 'AWP', NULL, 'Geomapper - Fase 1 pro Enada', 'Tool per mappatura rete AWP', 'Alta', 'Done', 'AWP-733', 'Jira', 'BU', NULL, 'Demand - BU', 'Normalizzazione e reperimento coordinate conclusa
Implementazioni chiuse
Effettuata seconda call di collaudo indata 07/02, confermate impressioni positive
Rilascio silente in data 08/02 (con CR su stato lavorazione)
Predisposizione ambiente per Demo di Enada', 'Test BU su Produzione
Verificare se mantenere riquadro Forfait sulla Dashboard per demo', '2024-02-20', NULL, '2024-02-08', '2024-02-08', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-031', 'AWP', NULL, 'Report "contatori 120/121 in errore"', 'Evoluzione del Report vs una gestione simil-cruscotto', 'Alta', 'Done', 'AWP-2411', 'Jira', 'IT', NULL, 'IT', 'Rilasciato in produzione', 'Chiudere verifiche lato Rete', '2025-12-30', NULL, '2025-12-31', '2025-12-31', '2025 Q4', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-032', 'AWP', '{"MGM Varie","LGP"}', 'Portale LGP', 'LGP | Rubrica Telefonica lato AWP_ sia lato GMT che LVR', 'Alta', 'Done', 'AWP-2591', 'Jira', 'BU', 'Lorenzo Bontempi', 'IT', 'Rilasciato in colloudo', 'In attesa collaudo', '2026-03-13', '2026-03-12', '2026-03-23', '2026-03-23', '2026 Q1', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-033', 'AWP', NULL, 'Richiesta integrazioni/modifiche Geomapper', '-', 'Alta', 'Done', 'AWP-1972', 'Jira', 'IT', 'Lorenzo Bontempi', 'GM/DEV', 'rilasciate le prime funzioni di reportistica e caricamento puntuale delle coordinate', 'Caricamento massivo', '2025-06-30', '2025-07-15', '2025-07-01', '2025-07-01', '2025 Q3', false, NULL, '21-60', '31-50') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-034', 'AWP', '{"Cruscotto AWP"}', 'Cruscotto AWP', 'Report A104 - Dashboard Controlli AWP', 'Alta', 'Done', 'AWP-2675', 'Jira', 'IT', 'Manuela Graziani', 'IT', 'Collaudo concluso', NULL, '2026-03-27', '2026-03-30', '2026-03-30', NULL, '2026 Q1', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-035', 'AWP', '{"Se-Gag"}', '-', 'Invio di una comunicazione mensile per le AWP non lette nel mese', 'Alta', 'Done', 'AWP-2636', 'Jira', 'IT', 'Manuela Graziani', 'IT', 'Creata in Jira il 23/02', 'Lavorare la cmfp per rilascio in prod', '2026-03-31', '2026-03-25', NULL, NULL, '2026 Q1', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-036', 'AWP', '{"Se-Gag"}', 'Sviluppo su SE-GAG per società Ricreativo B', 'Invio massivo delle PEC per la società Ricreativo B', 'Alta', 'Done', 'AWP-2690', 'Jira', 'IT', 'Manuela Graziani', 'IT', 'Sviluppo completato, rilasciato ma NON utilizzato', NULL, '2026-03-31', NULL, NULL, NULL, '2026 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-037', 'AWP', '{"Se-Gag","GAP"}', 'Modifica al motore di calcolo', 'Funzione di associazione costo rete agevolato per set prestabilito di AWP', 'Alta', 'Done', 'AWP-2621', 'Jira', 'BU', 'Lorenzo Bontempi, Manuela Graziani', 'Demand - ADI', 'Individuata soluzione basata su Contratti Condizionati
Sviluppi completati lato SE; MGM e GAP', 'Finalizzare rilascio in Porduzione', '2026-04-20', '2026-04-21', '2026-04-21', NULL, '2026 Q2', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-038', 'AWP', '{"Cruscotto AWP","Se-Gag"}', 'Implementazione lista AWP in errore su Se-Gag', 'Richiesta implementazione lista su SeGaG con AWP in errore – voce 724 per inaccessibilità sia per GMT che per LVR', 'Alta', 'Done', 'AWP-2734', 'Jira', 'BU', 'Manuela Graziani', 'IT', NULL, 'Sviluppo finito e rilasciato in prod per le verifiche; da varificare con commettenza', '2026-05-15', '2026-05-15', '2026-05-15', NULL, '2026 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-039', 'AWP', '{"DB"}', 'Reportistica di dettaglio "spettanze altri noleggiotori"', 'Reportistica quindicinale di dettaglio per entrambe i concessionari, relativa alle “spettanze altri noleggiatori”, simile a quella che già inviate per Aggi gs ss.', 'Alta', 'Done', 'AWP-2793', 'Jira', 'BU', 'Manuela Graziani', 'IT', NULL, 'Sviluppo rilasciato', '2026-06-30', '2026-05-15', '2026-05-15', NULL, '2026 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-040', 'CROSS', NULL, 'Estrazioni dati degli allegati 5/5a e 6/6a Esiti dei Controlli Concessori e scarico massivo degli Esiti', '-', 'Alta', 'Done', 'AWP-1114', 'Jira', 'IT', NULL, 'GM-DEV', 'Live', '-', '2024-10-01', NULL, '2024-10-01', '2024-10-01', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-041', 'CROSS', '{"DWH"}', 'Modello DWH AWP/VLT - budget versione', 'si richiede di visualizzare sui modelli di AWP e VLT le versioni 0 di budget.', 'Alta', 'Done', 'REP-570', 'Jira', 'BU', NULL, 'IT', 'Attività completata il 21/05.', NULL, '2026-06-30', '2026-05-21', '2026-05-21', '2026-05-21', '2026 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-042', 'CROSS', NULL, 'Definizione tracciati anagrafici', '-', 'Alta', 'Cancelled', 'SKSMIG-71', 'Jira', 'BU', NULL, 'SKS', 'prodotta prima elaborazione da sistemi', 'In attesa nuova fornitura dati', '2024-11-20', NULL, NULL, NULL, '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-043', 'VLT', '{"MGM varie"}', 'MGM_ABILITAZIONE SCARICO ELENCO BLOCCHI AMMINISTRATIVI VLT', 'Si richiede di creare una nuova funzione in MGM menù VLT e Blocco/Sblocco Sale VLT denominata ''Visualizza Storico'' (ACL: 184).
La funzione avrà i seguenti filtri di ricerca nell''accordion Filtri:

Codice Sede (like)
Denominazione Sede (like)
Denominazione Tir (like)
Motivo Blocco (tendina con Seleziona e gli stessi valori del Tipo Blocco di Inserisci Richiesta)
Data Esecuzione Blocco Da/A
 

La tabella risultante dalla ricerca sarà precaricata vuota all''ingresso in pagina, avrà scarico xls, personalizzazione campi e i seguenti valori: CODICE SEDE, DENOMINAZIONE SEDE, CODICE AAMS, INDIRIZZO, MOTIVO BLOCCO, DATA RICHIESTA BLOCCO, DATA ESECUZIONE BLOCCO, DATA RICHIESTA SBLOCCO, DATA ESECUZIONE SBLOCCO, ID TIR, DENOMINAZIONE TIR, ID ESERCENTE, DENOMINAZIONE ESERCENTE, NOTE RICHIESTA BLOCCO, NOTE RICHIESTA SBLOCCO.

 

Il nuovo tab sarà posizionato a destra dell''attuale Visualizza Richieste, il tab su cui si atterra di default al click della voce di menù resta comunque Visualizza Richieste.', 'Alta', 'Done', 'VLT-595', 'Jira', 'BU', 'Lorenzo Bontempi', 'IT', 'Prime implementazioni lavorate e rilasciate', 'Sviluppi in corso, in chiusura entro la settimana', '2026-05-29', '2026-06-11', NULL, NULL, '2026 Q2', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-044', 'VLT', '{"LGP","Se-Gag","Se-Ges","SAP","TIBCO"}', 'Relazioni commerciali', 'Relazioni commerciali - gestione per il caricamento', 'Alta', 'Done', 'BSS-895', 'Jira', 'IT', 'Lorenzo Bontempi, Manuela Graziani', 'IT', NULL, 'In corso sviluppi', '2026-03-31', NULL, NULL, NULL, '2026 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-045', 'VLT', '{"GAP","MGM","Se-Gag"}', 'Gestione addendum VLT per "affitto" di 3 modlli Novomatic (Fase1)', 'Sviluppo di un''interfaccia che consenta la gestione dei ratei su base Modello-Cifra-Tempo', 'Alta', 'Done', 'VLT-571', 'Jira', 'IT/BU', 'Manuela Graziani', 'IT', 'Condivisa soluzione
MGM sviluppo chiuso
Svolto showing in Dev con la BU (04/05)
Rilascio in prod effettuato', 'Finalizzare rilascio in produzione completo
Verifica congiunta da proporre direttamente in prod per il 26/5', '2026-03-31', '2026-05-13', '2026-05-13', NULL, '2026 Q2', false, 'La prima Baseline era stata idealmente fissata su una soluzione troppo snella e si è pertanto concordato di shiftare il rilascio per averne una più completa', '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-046', 'VLT', '{"DB"}', 'Monitoring su addendum NOVO', 'Presidio sui dati prodotti dal relativo sviluppo', 'Alta', 'Done', 'VLT-612', 'Jira', 'IT', 'Lorenzo Bontempi, Manuela Graziani', 'IT', NULL, 'Sviluppi in corso', '2026-06-30', '2026-06-30', NULL, NULL, '2026 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-047', 'VLT', NULL, 'Report Unico Anagrafico', 'Implementazione Nuovi Campi – Fase 1', 'Alta', 'Done', 'VLT-46', 'Jira', 'CSE + BU', 'Manuela Graziani', 'BU/demand', 'Risolte ultime tematiche relativa a:
- toponimi mancanti su alcuni Pdv (da mutuare info su ALBO)
- relazioni commerciali
NB: alimentazione giornaliera interrotta dal 6/11
Sono state aggiornate le tabelle per le relazioni commerciali
Problema su relazioni commerciali', '-in corso aggiornamento delle sale che insistono sul Report Unico Anagrafico
- relazioni commerciali: aggiornamento e relative conseguenti verifiche, (aggiornato al 23/11)', '2024-12-31', '2025-10-30', '2025-12-23', '2025-12-23', '2025 Q4', false, 'Progettualità complessa che ha risentito di numerose rilavorazioni sul fronte delle integrazioni con SAPCRM per le informazioni anagrafiche (relazioni)', '61-100', '50+') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-048', 'VLT', NULL, 'BPM', 'Fase 2', 'Alta', 'Cancelled', NULL, 'Manuale', 'BU', NULL, '-', 'Prima fase di analisi chiusa per quasi tutti i processi ma siamo in importante rilavorazione poiché molti dei processi disegnati non sono stabili e necessitano di redesign lato BU. Ove possibile è iniziata anche l’analisi di dettaglio IT e relativa progettazione.
SLOT RICHIESTO PER VLT', 'Analisi Interna e pianificazione
Previsti rilasci incrementali in Q2', '2024-12-31', '2025-12-30', NULL, NULL, '2025 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
