insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-097', 'AWP', NULL, 'Messaggio Informativo | Modulo LGP RIENTRO DA MANUTENZIONE STRAORDINARIA', '-', 'Media', 'Done', 'AWP-2070', 'Jira', 'IT', 'Lorenzo Bontempi', NULL, NULL, NULL, '2025-06-30', '2025-06-23', '2025-06-30', '2025-06-30', '2025 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-098', 'AWP', NULL, 'AWP - SEGAG -  Ingegnerizzazione invio comunicazioni PEC - lato GMT ', 'Gestione visualizzazione risposte PEC (non ricevute)', 'Media', 'Done', 'OT-938', 'Jira', 'IT', 'Manuela Graziani', 'ADI', 'Live', NULL, '2025-04-30', '2025-05-07', '2025-05-07', '2025-05-07', '2025 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-099', 'AWP', NULL, 'Cruscotto AWP', 'SE GAG | sezione Utility_(ID-Oggetto-Excel)', 'Media', 'Done', 'AWP-2004', 'Jira', 'IT', 'Manuela Graziani', 'Demand', 'Chiusa', 'Aggiornare JIRA', '2025-05-30', NULL, '2025-05-21', '2025-05-21', '2025 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-100', 'AWP', NULL, 'RICHIESTA MODIFICHE PORTALE CONTRATTI MGM LVR E GMT', 'migliorie', 'Media', 'Done', 'AWP-2121', 'Jira', 'IT', 'Lorenzo Bontempi', 'IT', 'Live', NULL, '2025-07-30', NULL, '2025-07-28', '2025-07-28', '2025 Q3', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-101', 'AWP', NULL, 'Cruscotto AWP', 'IMPLEMENTAZIONE blocco e sblocco programmato', 'Media', 'Done', 'AWP-1464', 'Jira', 'IT', 'Manuela Graziani', 'ADI', 'Presentazione ai gruppi interessati effettuata il 23/05', 'chiusura Fase1 prevista entro il 30/05
Fase 2 con sfridi da lavorare successivamente: necessaria nuova issue', '2025-04-30', '2025-06-03', '2025-06-06', '2025-06-06', '2025 Q2', false, 'L''implementazione è stata rivisitata più volte e rilavorata senza aprire nuova issue', '21-60', '31-50') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-102', 'AWP', NULL, 'LGP - Inserimento Pratica Manutenzione con Ferie già presenti', '-', 'Media', 'Done', 'AWP-2304', 'Jira', 'IT', 'Lorenzo Bontempi, Manuela Graziani', 'IT', 'LIVE', NULL, '2025-09-30', NULL, '2025-10-15', '2025-10-15', '2025 Q3', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-103', 'AWP', NULL, 'Conto Giudiziale', 'Cruscotto GAP - Integrazione elaborazione manutenzioni con tombale', 'Media', 'Done', 'AWP-GAP59', 'Jira', 'IT', 'Nello', 'IT', NULL, NULL, '2026-02-16', NULL, '2026-02-13', '2026-02-13', '2026 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-104', 'AWP', NULL, 'Automatismo versamenti preu AAMS', '-', 'Media', 'Done', 'AWP-2316', 'Jira', 'IT', 'Lorenzo Bontempi, Manuela Graziani', NULL, 'sviluppi chiusi lato MGM, predisposta RFIO', 'Collaudare', '2025-10-22', NULL, '2025-10-23', '2025-10-23', '2025 Q4', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-105', 'AWP', NULL, 'MGM Contratti - pulsante per cancellazione primo contratto', '-', 'Media', 'Done', 'AWP-2338', 'Jira', 'IT', 'Lorenzo Bontempi', 'IT', 'da dev a prod release', 'Sviluppo terminato e rilascio da effettuare insieme a bimestrale', '2025-12-31', NULL, '2025-10-23', '2025-10-23', '2025 Q4', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-106', 'AWP', NULL, 'PEC Infocert', '-', 'Media', 'Done', 'AWP-2123', 'Jira', 'IT', 'Manuela Graziani', 'ADI', 'effettuati test di ricezione, problemi a livello di indirizzo --> network
test finiti
''test parte invio (manca la parte di proxy) da lavorare con CMFP dedicata (effettuato)
Creato indirizzo in condivisione con il gruppo di Samantha
LIVE', NULL, '2025-09-30', NULL, '2025-10-15', '2025-10-15', '2025 Q3', false, '- 16/09: sviluppo subordinato ad   attività di test con Sogei', '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-107', 'AWP', NULL, 'GAP', 'Ottimizzazione procedura previsione giornaliera', 'Media', 'Done', 'AWP-2391', 'Jira', 'IT', 'Nello', NULL, NULL, NULL, '2025-12-31', '2025-11-07', '2025-11-10', '2025-11-10', '2025 Q4', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-108', 'AWP', NULL, 'LGP', 'Generazione richieste di assistenza pilotate ed inoltro mail', 'Media', 'Done', 'AWP-1909', 'Jira', 'BU', 'Lorenzo Bontempi', 'BU', 'Revisione ed approvazione RU', 'chiudere implementazione', '2025-05-30', NULL, '2025-05-09', '2025-05-09', '2025 Q2', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-109', 'AWP', NULL, 'MGM - Portale Contratti', 'introduzione funzionalità modifica modello', 'Media', 'Done', 'OT-863', 'Jira', 'IT', 'Nello, Lorenzo Bontempi', 'IT', 'implementazione lato DB chiusa, da analysis a test', 'chiudere test', '2025-04-11', NULL, '2025-04-10', '2025-04-10', '2025 Q2', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-110', 'AWP', NULL, 'Richiesta di una vista sui contatori annuali della AWP', '-', 'Media', 'Done', 'AWP-2460', 'Jira', 'IT', NULL, 'IT', 'Rilasciata ad AgeSoft', 'In attesa OK da AgeSoft', '2025-12-28', NULL, '2026-01-09', '2026-01-09', '2025 Q4', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-111', 'AWP', '{"LGP"}', 'LGP', 'Integrazione per il ticket blocco e sblocco ferie', 'Media', 'Done', 'AWP-2650', 'Jira', 'IT', 'Lorenzo Bontempi', 'IT', 'Rilascio lato LGP', 'Se da rilasciare separatamente dal pacchetto Zen da valutare extra effort per scorporazione
Concordato rilascio in Prod. il 09/06', '2026-03-27', '2026-06-09', NULL, NULL, '2026 Q2', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-112', 'AWP', NULL, 'Cruscotto AWP  LVR', '-', 'Media', 'Cancelled', 'AWP-1549', 'Jira', 'IT', NULL, '-', 'attiività spostata su DWH', NULL, '2024-12-12', NULL, NULL, NULL, '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-113', 'AWP', NULL, 'MGM-Gestione utente', 'Aggiunta campo note in fase di riattivazione delle utenze cessate', 'Media', 'Done', 'AWP-1731', 'Jira', 'IT', 'Lorenzo Bontempi', 'GM-DEV', 'messo in done in data 06/02', NULL, '2025-02-07', NULL, '2025-02-06', '2025-02-06', '2025 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-114', 'AWP', '{"ZenDesk"}', 'AWP su Zendesk', 'AWP -Introduzione del WF completo di  Trouble Ticketing su Zendesk', 'Media', 'Done', 'AWP-1371', 'Jira', 'IT', NULL, 'Cloudsherpa + TIBCO', 'Richiesto eventuale rilascio in produzione non prima di Settembre', 'Riavviare e chiudere Ciclo di test/collaudo', '2025-03-31', '2026-03-31', NULL, NULL, '2026 Q1', false, NULL, '21-60', '31-50') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-115', 'AWP', '{"SEGAG"}', 'Processo di certificazione', 'Allert per tracciamento esercizi con AWP d''altre reti', 'Media', 'Cancelled', 'AWP-2286', 'Jira', 'BU', 'Lorenzo Bontempi, Manuela Graziani', 'IT', 'modificata issue jira
Verificata l''impossibilità di usare le logiche di esclusione del Geomapper
Attualmente in stand-by poiché file inviato da networking non è adatto allo scopo', 'In attesa di aggiornamenti lato BU', '2026-03-31', NULL, NULL, NULL, '2026 Q1', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-116', 'AWP', NULL, 'Report A104 - DASHBOARD CONTROLLI AUTORITA'' da rendere visibile a Cruscotto AWP consulenti', '- ', 'Media', 'Done', 'AWP-2369', 'Jira', 'IT', 'Manuela Graziani', 'IT', 'Rilascio in verifica in prod anche con successivi enanchement', 'Rilasciare le richieste emerse durantte il collaudo', '2025-11-07', '2025-11-28', '2025-12-31', '2025-12-31', '2025 Q4', false, 'Attività allumgatasi per richieste emerse durante il collaudo', '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-117', 'AWP', NULL, 'Richiesta invio mail info su attivazioni LGP', '-', 'Media', 'Done', 'AWP-2546', 'Jira', 'IT', 'Lorenzo Bontempi, Manuela Graziani', 'IT', 'Rilasciato invio sintetico ogni lunedì', NULL, '2026-03-31', NULL, '2026-02-03', '2026-02-03', '2026 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-118', 'AWP', NULL, 'Creazione tipologia blocchi GMT e  LVR', '- ', 'Media', 'Done', 'AWP-1905', 'Jira', 'IT', 'Manuela Graziani', 'ADI', 'in analisi', NULL, '2025-03-30', NULL, '2025-03-18', '2025-03-18', '2025 Q1', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-119', 'AWP', NULL, 'AWP - Ingegnerizzazione invio comunicazioni PEC - lato Gmt - LVR ', 'Invio pec automatiche/schedulate nel nuovo sistema', 'Media', 'Done', 'OT-791', 'Jira', 'IT', 'Manuela Graziani', 'ADI', 'Chiusa', '-', '2025-02-28', '2025-03-14', '2025-04-01', '2025-04-01', '2025 Q1', false, 'problematiche di esercizio e attività sul portale contratti, problemi di rete per apertura porta', '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-120', 'AWP', NULL, 'Richiesta estrapolazione dati MGM lato GMT e LVR', '- ', 'Media', 'Done', 'AWP-2300', 'Jira', 'IT', 'Lorenzo Bontempi', 'IT', 'in produzione', NULL, '2025-09-30', NULL, '2025-09-22', '2025-09-22', '2025 Q3', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-121', 'AWP', NULL, 'LGP - Controllo su IP', '-', 'Media', 'Done', 'AWP-2314', 'Jira', 'IT', 'Lorenzo Bontempi', 'IT', 'LIVE', NULL, '2025-12-30', NULL, '2025-10-15', '2025-10-15', '2025 Q4', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-122', 'AWP', NULL, 'IMPLEMENTAZIONE REPORT 57 TIR TIPO CONTRATTI', '- ', 'Media', 'Done', 'AWP-1894', 'Jira', 'IT', 'Manuela Graziani', 'ADI', NULL, 'da chiudere in questa settimana post controlli sulla bimestrale', '2025-03-31', NULL, '2025-03-21', '2025-03-21', '2025 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-123', 'AWP', NULL, 'MGM - Aggiunta funzione per impostazione date campagna albo ADM', '-', 'Media', 'Done', 'AWP-2446', 'Jira', 'IT', 'Lorenzo Bontempi', 'IT', 'Sviluppi terminati', 'predisposizione rilascio in Collaudo', '2026-03-31', NULL, '2026-02-01', '2026-02-01', '2026 Q1', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-124', 'AWP', NULL, 'Cruscotto AWP', 'Modifiche al Report 100 - Interrogazione massiva AWP', 'Media', 'Done', 'AWP-1854', 'Jira', 'IT', 'Manuela Graziani', 'ADI', 'Nuova, censita in data 28/02', NULL, '2025-03-07', NULL, '2025-03-19', '2025-03-19', '2025 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-125', 'AWP', NULL, 'Cruscotto AWP', 'Storico Report R025 cruscotto lato GMT e LVR', 'Media', 'Done', 'AWP-1601', 'Jira', 'IT', NULL, 'ADI', 'concluso in data 10/02', '-', '2024-12-31', NULL, '2025-02-10', '2025-02-10', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-126', 'AWP', NULL, 'LGP | Aggiunta codice modello e relativo filtro sia su GMT che LVR', '-', 'Media', 'Done', 'AWP-1748', 'Jira', 'IT', NULL, 'GM- DEV', 'in corso di rilascio', NULL, '2024-12-31', NULL, '2025-01-29', '2025-01-29', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-127', 'AWP', NULL, 'Report R099 - Elenco delle slot _ lato GMT/LVR', '-', 'Media', 'Done', 'AWP-1544', 'Jira', 'IT', NULL, '-', NULL, NULL, '2024-11-27', NULL, '2024-11-27', '2024-11-27', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-128', 'AWP', NULL, 'Modello Dati AWP - aggiornamento campo "Cluster AWP" con Rete Gioco Italia', '-', 'Media', 'Done', 'AWP-1319', 'Jira', 'BU', NULL, 'DWH', 'verificare chiusura
da test a last done', '-', '2024-10-02', NULL, '2024-10-02', '2024-10-02', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-129', 'AWP', NULL, 'Nuovo report su pdv con awp di proprietà del gestore senza ctr associati', '-', 'Media', 'Done', 'AWP-977', 'Jira', 'IT', NULL, 'BU', 'LIVE', '-', '2024-06-19', NULL, '2024-06-19', '2024-06-19', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-130', 'AWP', NULL, 'Modello Dati AWP - aggiornamento campo "Cluster AWP"', '-', 'Media', 'Done', 'AWP-1108', 'Jira', 'IT', NULL, 'DWH', 'effettuato passaggio con Pisauro, in corso risoluzione a seguito di piccolo problema tecnico', NULL, '2024-04-24', NULL, '2024-04-24', '2024-04-24', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-131', 'AWP', NULL, 'Rendiconto TIR AWP GMNT: allineamento ad LVR', '-', 'Media', 'Done', 'AWP-746', 'Jira', 'IT', NULL, 'BU', 'Live', '-', '2024-05-20', NULL, '2024-05-20', '2024-05-20', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-132', 'AWP', NULL, 'GAP', 'AdM-Conguaglio Annuale', 'Media', 'Done', 'OT-263', 'Jira', 'IT', NULL, 'GM-DEV + ADI', 'Ricevuto file da AdM in data 08/03
Controlli GMNT ok
Controlli LVR ok', 'Avviare verifiche con file ricevuto da AdM su base annuale versione precedente alle modifiche in atto per corretta gestione Costo Rete per gli scaglioni  di modo da anticipare eventuali macro squadrature
Intergrazione della procedura nel tool di lancio confronto da operare a bimestrale chiuso
', '2024-05-13', NULL, '2024-05-13', '2024-05-13', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-133', 'AWP', NULL, 'Portale LGP GMNT e LVR ', 'Aggiunta info e stato Bloccato da DA', 'Media', 'Done', 'AWP-565', 'Jira', 'IT', NULL, 'ADI', 'Live ', NULL, '2024-02-12', NULL, '2024-02-12', '2024-02-12', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-134', 'AWP', NULL, 'Cruscotto AWP', 'Automatismo invio comunicazioni peo e PEC - Lato GMNT - LVR', 'Media', 'Done', 'AWP-724', 'Jira', 'IT', NULL, '-', 'Mandate le mail prima di ferragosto
creare OT per le parti mancanti
Da analisi a last done', 'Parte delle ricevute, gestione delle stesse', '2024-09-03', NULL, '2024-09-03', '2024-09-03', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-135', 'AWP', NULL, 'Cruscotto AWP', 'AWP post manutenzione - implementazione sistema per ripristino post manutenzione e monitoraggio lavorazioni', 'Media', 'Cancelled', 'AWP-400', 'Jira', 'IT', NULL, 'ADI', 'Cancellato in data 12/02/2024 per evitare possibile errori di procedura (non esiste una soluzione automatica efficiente)', '-', '2024-02-12', NULL, NULL, NULL, '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-136', 'AWP', NULL, 'GAP', 'Cruscotto PREU - Ricerca Estratti conto', 'Media', 'Done', 'OT-564', 'Jira', 'IT', NULL, 'GM-DEV', 'LIVE', NULL, '2024-07-01', NULL, '2024-07-01', '2024-07-01', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-137', 'AWP', NULL, 'GAP', 'Fornitura ADE per concessionaria LVR', 'Media', 'Done', 'OT-597', 'Jira', 'IT', NULL, 'GM-DEV', 'Mandati tracciati', '-', '2024-07-31', NULL, '2024-07-31', '2024-07-31', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-138', 'AWP', NULL, 'Geomapper', 'Geomapper AWP pro PdV LTM- GoLive Q3 2024', 'Media', 'Done', 'AWP-1293', 'Jira', 'IT', NULL, 'GM-DEV', 'Apertura a tutta la rete dei service
da test a last done', 'sviluppo su backoffice', '2024-08-30', NULL, '2024-08-30', '2024-08-30', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-139', 'AWP', NULL, 'Cruscotto AWP', 'GMT/LVR: Errore nella Trasmissione', 'Media', 'Done', 'AWP-1182', 'Jira', 'IT', NULL, 'GM-DEV', 'LIVE', '-', '2024-07-04', NULL, '2024-07-04', '2024-07-04', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-140', 'AWP', NULL, 'AWP - Automatismo invio comunicazioni PEC pro RIES ', 'implementazione dell''individuazione automatica dei pdv per gestore ancora privi di rinnovo e relativo invio sollecito via mail', 'Media', 'Done', 'OT-782', 'Jira', 'IT', NULL, 'ADI', 'Deploy e demo effettuati per GMNT
da test a Prod release
Deploy LVR fatto
da prod a last done', 'fine tuning sulla visualizzazione', '2024-05-20', NULL, '2025-05-21', '2025-05-21', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-141', 'AWP', NULL, 'Cruscotto AWP', 'Implementazione Report E1 (724 LVR/GMT)', 'Media', 'Done', 'AWP-638', 'Jira', 'IT', NULL, '-', 'LIVE', '-', '2024-06-06', NULL, '2024-06-06', '2024-06-06', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-142', 'AWP', NULL, 'Cruscotto AWP', 'Implementazione Report R025 LVR/GMT', 'Media', 'Done', 'AWP-637', 'Jira', 'IT', NULL, '-', 'LIVE', NULL, '2024-05-31', NULL, '2024-05-31', '2024-05-31', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-143', 'AWP', NULL, 'Cruscotto AWP', 'inserimento indirizzi PEO su report R0215 e report R0219 cruscotto GMT e LVR', 'Media', 'Done', 'AWP-1271', 'Jira', 'IT', NULL, 'ADI', 'LIVE', '-', '2024-07-12', NULL, '2024-07-12', '2024-07-12', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-144', 'AWP', NULL, 'GAP', 'Integrazione processo 25° Rendicontazione per LVR (Con adeguamenti necessari) ', 'Media', 'Done', 'OT-259', 'Jira', 'IT', NULL, 'IT', 'Live', 'completare caricamento dati forniti da periferia + applicare il 50-50 + generazione annuale (WIP)', '2024-05-13', NULL, '2024-05-13', '2024-05-13', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
