insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-049', 'VLT', NULL, 'GMNT_Modifiche dashbord/abilitazione utenze standard', '-', 'Alta', 'Done', 'VLT-197', 'Jira', 'IT', 'Manuela Graziani', 'BU', NULL, NULL, '2025-01-23', NULL, '2025-01-23', '2025-01-23', '2025 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-050', 'VLT', NULL, 'Report periodico elenco completo sale Gaming con ID Betting ', '-', 'Alta', 'Done', 'REP-158', 'Jira', 'BU', NULL, 'BU', 'colloquio con BU effettuato', 'da rilasciare in produzione con vlt-410', '2025-02-28', '2025-05-15', '2025-04-29', '2025-04-29', '2025 Q2', false, 'la richiesta si è collegata a quella del Master Unico Anagrafico e quindi le lavorazioni sono andate a braccetto', '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-051', 'VLT', NULL, 'Cruscotto VLT', 'Sviluppo VLT-CRUSCOTTO ROLL OUT (ROD)', 'Alta', 'Done', 'VLT-329', 'Jira', 'IT', 'Manuela Graziani', 'IT', 'LIVE
da prod release a last done', NULL, '2025-02-15', '2025-02-28', '2025-02-28', '2025-02-28', '2025 Q1', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-052', 'VLT', NULL, 'VLT - Reingegnerizzazione Rettifiche ', 'Rettifiche VLT - Storno e Ricalcoli via SEGAG', 'Alta', 'Done', 'OT-863', 'Jira', 'IT', 'Nello', 'IT', 'in produzione', 'in attesa di test', '2025-02-28', '2025-03-06', '2025-03-06', '2025-03-06', '2025 Q1', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-053', 'VLT', '{"DWH"}', 'Nuova logica campo "Stato_Sala" e rimozione magazzini su report Parco Macchine', '
Richiesta nuova logica del campo "Stato_Sala" presente tra i nuovi campi da integrare nel RUA. Di seguito il dettaglio:

“Giocante”, se nel rendicontato si ha bet>0 e data collaudo presente;
“Non giocante”, se nel rendicontato si ha bet<0 e data collaudo presente;
“Prospect”, si considereranno le sale con bet>0, ma senza la data di collaudo;
Per i primi due punti sarà integrazione della condizione della data di collaudo rispetto all’attuale AS-IS.

Inoltre, andranno rimossi dalla visualizzazione e dall''export i magazzini dal report RUA sezione parco Macchine.', 'Alta', 'Analysis', 'REP-641', 'Jira', 'IT', NULL, 'IT', NULL, NULL, '2026-09-30', NULL, NULL, NULL, '2026 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-054', 'VLT', NULL, 'LGP - chiusura interventi manutentori', 'Inserimento OTP', 'Alta', 'Done', 'CCLO-275', 'Jira', 'BU', NULL, 'GM-DEV', 'verificato il corretto funzionamento del servizio anche con TIBCO
chiusa implementazione Agesoft
organizzato collaudo per il 4/12
da dev a last done', 'abilitazione campo front-end a chiusura collaudo altri sistemi', '2024-12-31', NULL, '2024-12-16', '2024-12-16', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-055', 'VLT', NULL, 'Dashboard BI', 'Modello Power BI - Aggiunta conteggio VLT Giocanti', 'Alta', 'Done', 'OT-882', 'Jira', 'IT', NULL, 'IT', 'nuova, necessaria per SM
in test', 'chiudere verifiche lato ADI', '2025-01-31', '2025-02-07', '2025-02-07', '2025-02-07', '2025 Q1', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-056', 'VLT', NULL, 'Nuovo IR LVR', 'Introduzione della figura IV Incaricato (IR) in LVR', 'Alta', 'Done', 'VLT-250', 'Jira', 'BU', NULL, 'BU + IT', '-', '-', '2024-12-31', NULL, '2024-12-19', '2024-12-19', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-057', 'VLT', NULL, 'Classificazione COMMERCIALE Modelli VLT AdM', '-', 'Alta', 'Done', 'REP-284', 'Jira', 'IT', NULL, 'IT', NULL, NULL, '2025-06-25', NULL, '2025-07-17', '2025-07-17', '2025 Q2', false, 'incrocio di attività', '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-058', 'VLT', '{"Se-Gag"}', 'Omnipay', 'Fornitura anagrafiche Sale e Ticket Vincenti', 'Alta', 'Prod. Release', 'PRVLT-86', 'Jira', 'BU', 'Lorenzo Bontempi, Manuela Graziani', 'BU', 'Set dati messo a disposizione
Fornite a BU le anagrifiche di sale presentanti ticket non pagati (mail inviata il 05/02)', 'Collaudo terminato. In attesa di pianificazione rilascio in Prod. (lato Digital)', '2025-12-31', '2026-01-31', NULL, NULL, '2026 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-059', 'VLT', '{"SAP"}', 'Modifica aliquota flussi ARES vs GSPA e LVR', NULL, 'Alta', 'Cancelled', 'VLT-576', 'Jira', 'IT', NULL, 'IT', 'Ticket rigettato in data 09/04 a seguito di comunicazione della committenza.', NULL, NULL, NULL, NULL, NULL, 'TBD', false, 'A seguito di ulteriori approfondimenti non ci sono i presupposti per lo sviluppo richiesto. La committenza utilizzerà una procedura alternativa (manuale).', NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-060', 'VLT', '{"MGM"}', 'Integrazione della virgola per il BONUS ANNUALE', NULL, 'Alta', 'Done', 'VLT-578', 'Jira', 'IT/BU', 'Lorenzo Bontempi', 'IT', 'Rilascio in collaudo', 'chiusura collaudo', '2026-03-12', NULL, '2026-03-23', '2026-03-23', '2026 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-061', 'VLT', NULL, 'IR GMNT', 'Adeguamento del core per gestione percentuale netta del TIR e conseguenze', 'Alta', 'Done', 'VLT-346', 'Jira', 'BU', NULL, 'SAP', 'effettuata call con Sistemi in cui si è deciso di non modificare i flussi ma di battere sui campi no IR
effettuata call giovedì 7/11 con SAP
Implementazione modifica su dovuto concessionario chiusa;
predisposizione dati di test
Implementazione modifica su dovuto concessionario chiuso test e collaudo
da prod. Release a last done', 'Rilascio SAP previsto il 2/01

', '2024-12-31', NULL, '2025-01-02', '2025-01-02', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-062', 'VLT', NULL, 'MGM', 'Implementazione Attivazione straordinaria Tir senza Iscrizione come ALTRO', 'Alta', 'Done', 'VLT-234', 'Jira', 'BU', NULL, 'TCH - GM-Dev', 'LIVE il 04/04', NULL, '2024-04-04', NULL, '2024-04-04', '2024-04-04', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-063', 'VLT', NULL, 'Bonus Annuale GMNT', 'Implementazione del Motore di calcolo Bonus anche per GMNT', 'Alta', 'Done', 'VLT-150', 'Jira', 'CdG + Amm.e', NULL, 'BU', 'Live', NULL, '2024-08-30', NULL, '2024-08-30', '2024-08-30', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-064', 'VLT', NULL, 'IGM - Bonus mensili', 'Implementazione su SEGAG di 4 nuove tipologie di bonus mensili', 'Alta', 'Done', 'VLT-113', 'Jira', 'BU', NULL, 'BU', 'Rilascio effettuato
Soggetti+bonus forniti', 'Chiudere i test con supporto delle evidenze sui mesi passati da parte del BU', '2024-02-05', NULL, '2024-02-05', '2024-02-05', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-065', 'VLT', '{"Cruscotto VLT"}', 'Cruscotto VLT', 'Implementazioni Dashboard VLT_1 - Modifiche di carattere generale per la homepage e per le attività', 'Alta', 'Done', 'VLT-130', 'Jira', 'IT', NULL, 'ADI', 'Sulla parte 6.1 del documento, si è eseguito:
- eliminazione colonna "macrogruppo attività"
- possibilità di eliminare un ticket in qualunque momento della lavorazione
- unione attività "dismissioni VLT e cessazioni VLT" in unica tipologia', 'Chiusura verifiche on field', '2024-01-15', NULL, '2024-01-15', '2024-01-15', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-066', 'VLT', '{"DWH"}', 'Relazioni Commerciali', 'Relazioni commerciali - Modifica Query DWH', 'Alta', 'Done', 'REP-546', 'Jira', NULL, NULL, 'Demand', 'Fornite le query lato ADI', 'verificare nuovo outputo in BS', '2026-04-17', '2026-04-27', '2026-04-27', NULL, '2026 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-067', 'VLT', NULL, 'EC Annuale LVR', 'modifche al lay-out', 'Alta', 'Done', 'VLT-216', 'Jira', 'BU', NULL, 'SAP', 'Chiarito il Layout lato LVR
Sviluppi chiudi', 'LIVE', '2024-03-25', NULL, '2024-03-25', '2024-03-25', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-068', 'VLT', '{"GAP"}', 'Modifica al Motore Bonus VLT', 'Automazione lancio ANNUALE del Motore Bonus VLT', 'Alta', 'Analysis', 'VLT-603', 'Jira', 'IT', 'Lorenzo Bontempi', 'IT', 'Analisi iniziata il 13/7', 'Chiudere analisi e stime', '2026-10-30', NULL, NULL, NULL, '2026 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-069', 'VLT', '{"Se-Gag"}', 'SeGag', 'Modifica al Motore Bonus mensili (IGM-like)', 'Alta', 'Done', 'VLT-113', 'Jira', 'BU', NULL, 'BU', 'Implementazione conclusa', '-', '2024-02-07', NULL, '2024-02-07', '2024-02-07', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-070', 'VLT', NULL, 'Bonus VLT', 'Modulo LVR', 'Alta', 'Done', 'VLT-150', 'Jira', 'Amm.e + BU', NULL, 'BU - Demand', 'LIVE', 'GMNT: sarebbe opportuno chiudere la definizione dei modelli per implementarne i comportamenti e verificarne i risultati in parallelo alla normale lavorazione annuale', '2024-01-12', NULL, '2024-01-12', '2024-01-12', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-071', 'VLT', '{"DWH"}', 'Evolutive Analisi del contesto - Dashboard VLT', NULL, 'Alta', 'To Start', 'REP-598', 'Jira', 'BU', NULL, 'IT', NULL, 'Attività da pianificare. Inizio dopo sviluppo RUA fase 2', '2026-09-30', NULL, NULL, NULL, '2026 Q3', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-072', 'VLT', '{"DB"}', 'Risoluzione problemi rettifiche vlt per dati anomali', 'Modifiche per la gestione dei dati anomali', 'Alta', 'Test', 'VLT-613', 'Jira', 'IT', 'Lorenzo Bontempi', 'IT', NULL, 'Sviluppi in corso', '2026-07-17', NULL, NULL, NULL, '2026 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-073', 'VLT', '{"GAP"}', 'VLT - Modifica al motore dei bonus VLT - Stima previsionale infrannuale', 'Automazione lancio PREVISIONALE del Motore Bonus VLT', 'Alta', 'On Hold', 'VLT-587', 'Jira', 'BU', 'Lorenzo Bontempi', 'IT', 'Creata Issue generica ma stabilito di lavorare innanzitutto sull''Automazione del lancio a fine anno
Concordata priorità su anno corrente da accordare allo sviluppo sull''automazione del lancio annuale', NULL, '2027-03-31', NULL, NULL, NULL, '2027 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-074', 'AWP', '{"LGP","ZENDESK"}', 'LGP Vs ZenDesk', 'Sistema di ticketing tra LGP e ZenDesk', 'Media', 'Done', 'AWP-301', 'Jira', 'IT', 'Lorenzo Bontempi', 'Demand+AWP-DEV+TIBCO', 'IT iniziati prima di Natale, in corso
Fatta riunione 05/02
Incontro sostenuto con committenza il 24/02
chiusa seconda sessione di verifica il 17/4', 'In corso incontri di UAT con la committenza
Gestire CR bloccante per gestione del rapportino giornaliero sui Ticket in LGP
Prevista chiusura post migrazione (fermo settimana 07/04-15/04).
Concludere ultime modifiche richieste', '2024-12-31', '2026-06-09', NULL, NULL, '2026 Q2', false, NULL, '61-100', '50+') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-075', 'AWP', '{"MGM varie"}', 'Tool estrazione rendiconti MGM', 'Introduzione di alcune modifiche', 'Media', 'UAT Release', 'AWP-2880', 'Jira', 'IT', 'Lorenzo Bontempi, Manuela Graziani', 'IT', 'Sviluppi in corso', NULL, '2026-09-30', '2026-07-17', NULL, NULL, '2026 Q3', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-076', 'AWP', NULL, 'Ingegnerizzazione calcolo conguaglio LVR/GMT + Interfaccia', '-', 'Media', 'Done', 'AWP-2248', 'Jira', 'IT', 'Lorenzo Bontempi, Manuela Graziani', 'IT', 'Chiuso sviluppo', 'Verifica interna con ADI', '2025-12-30', '2026-01-15', '2026-01-13', '2026-01-13', '2026 Q1', false, NULL, '21-60', '31-50') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-077', 'AWP', '{"MGM"}', 'Sviluppo contratto LVR – ampliamento soggetti', '- ', 'Media', 'On Hold', 'AWP-2317', 'Jira', 'IT', NULL, 'BU + Demand', 'incontro effettuato', 'in attesa di fb
Fissare un incontro con Irene Salvati per feedback (coinvolgimento di Fabrizio Severoni, Nello Città, Lorenzo Bontempi)', NULL, NULL, NULL, NULL, 'TBD', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-078', 'AWP', '{"ZenDesk"}', 'IVR ', 'Alberatura IVR AWP', 'Media', 'On Hold', 'AWP-1162', 'Jira', 'IT', 'Lorenzo Bontempi, Manuela Graziani', 'Demand', 'Documenti funzionali inviati ai soggetti del caso
in corso incontri tecnici per fattibilità preliminare
Inviata nuova versione del RU in data 08/05
impatto su LGP da quantificare con Melania
', 'In attesa riattivazione progetto e revisione RU da committenza', '2026-09-30', NULL, NULL, NULL, '2026 Q3', false, NULL, '61-100', '50+') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-079', 'AWP', NULL, 'Sviluppo portale MGM per calcolo costo rete', '-', 'Media', 'Done', 'AWP-2046', 'Jira', 'IT', 'Nello, Lorenzo Bontempi', NULL, 'Live', NULL, '2025-07-30', NULL, '2025-07-28', '2025-07-28', '2025 Q3', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-080', 'AWP', NULL, 'Visualizzazione spettanza noleggiatore sul rendiconto del Tir', '-', 'Media', 'Cancelled', 'AWP-2434', 'Jira', NULL, NULL, 'Demand', 'Considerato il RU sulla quota Noleggiatore spostata tutta in capo al Concessionario, Iniziativa Cancellata', NULL, '2026-01-31', NULL, NULL, NULL, '2026 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-081', 'AWP', NULL, 'LGP | sia lato GMT che LVR_NUOVO MESSAGGIO ', '-', 'Media', 'Done', 'AWP-2577', 'Jira', 'IT', 'Lorenzo Bontempi', NULL, 'Live', NULL, '2026-03-31', '2026-02-03', '2026-02-04', '2026-02-04', '2026 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-082', 'AWP', NULL, 'LGP - Oscuramento CNTTOTOT per Interni ', '-', 'Media', 'Done', 'AWP-2361', 'Jira', 'IT', 'Lorenzo Bontempi', NULL, 'Live', NULL, '2026-03-31', '2026-02-03', '2026-02-04', '2026-02-04', '2026 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-083', 'AWP', NULL, 'GAP', 'Aggiornamento automatico viste materializzate', 'Media', 'Done', 'OT-596', 'Jira', 'IT', 'Nello', 'GM-DEV', 'Il db non riesce ad aggiornare le viste in automatico ad ogni lancio di eventuali ricalcoli (in standby, se ne riparla post estate)
Riavviata attività in data 06/05
sviluppo terminato', 'chiudere implementazioni e test
da iniziare test in settimana', '2025-06-30', '2025-05-30', '2025-06-04', '2025-06-04', '2025 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-084', 'AWP', NULL, 'LGP - Rework analisi allarmi per accessi', '- ', 'Media', 'Done', 'AWP-2463', 'Jira', 'IT', 'Lorenzo Bontempi', 'IT', 'Lavorata anche durante chiusura
Chiusura sviluppi 16/01', 'Test in corso', '2026-01-31', NULL, '2026-01-27', '2026-01-27', '2026 Q1', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-085', 'AWP', '{"GAP"}', 'Modifica al motore di calcolo', 'Gestione della Chiusura retroattiva del calcolo del costo rete incrementale', 'Media', 'Done', 'AWP-2669', 'Jira', 'IT', 'Nello', NULL, 'Sviluppi avviati', 'Chiudere verifiche interne per successivo passaggio in pord', '2026-05-29', NULL, NULL, NULL, '2026 Q2', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-086', 'AWP', NULL, 'Cruscotto AWP', 'Richiesta invio PEC lato GMT e LVR', 'Media', 'Done', 'AWP-2116', 'Jira', 'IT', 'Manuela Graziani', 'ADI', 'chiusa', NULL, '2025-06-27', NULL, '2025-06-27', '2025-06-27', '2025 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-087', 'AWP', NULL, 'Cruscotto AWP', 'Nuovo allarme per disallineamento AWP/PDA Lato GMNT e LVR', 'Media', 'Done', 'AWP-1812', 'Jira', 'IT', 'Manuela Graziani', 'ADI', 'mandato in uat il giorno 06/03', '-', '2025-03-31', '2025-06-30', '2025-05-06', '2025-05-06', '2025 Q2', false, 'Attività a bassa priorità lavorata a best effort', '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-088', 'AWP', NULL, 'MGM', 'Scheda soggetto - campi di ricerca ', 'Media', 'Done', 'AWP-2204', 'Jira', 'IT', 'Lorenzo Bontempi', 'GM - DEV', 'sviluppo previsto in settimana', 'rilascio al collaudo', '2025-09-15', NULL, '2025-09-11', '2025-09-11', '2025 Q3', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-089', 'AWP', '{"LGP"}', 'LGP', 'Identificazione ip della whitelist su sezioni LGP', 'Media', 'Done', 'AWP-2639', 'Jira', 'IT', 'Lorenzo Bontempi', 'GM - DEV', 'Sviluppi chiusi
LIVE', 'In preparazione pacchetto per rilascio in UAT', '2026-03-13', NULL, '2026-03-23', '2026-03-23', '2026 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-090', 'AWP', NULL, 'LGP - Gestione logout su scadenza token e switch multiatt ', '-', 'Media', 'Done', 'AWP-2207', 'Jira', 'IT', 'Lorenzo Bontempi', 'GM-DEV', 'in corso', NULL, '2025-08-31', NULL, '2025-08-21', '2025-08-21', '2025 Q3', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-091', 'AWP', NULL, 'Richiesta aggiornamento indirizzo del Magazzino Logistica LOTTOMATICA', '-', 'Media', 'Done', 'AWP-2211', 'Jira', 'IT', 'Lorenzo Bontempi', 'GM-DEV', 'Live', NULL, '2025-08-31', NULL, '2025-07-28', '2025-07-28', '2025 Q3', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-092', 'AWP', NULL, 'Cruscotto AWP', 'Lavorazione su base PdV (collegata alla Jira AWP-396)', 'Media', 'Done', 'AWP-622', 'Jira', 'IT', 'Manuela Graziani', 'BU', 'rimessa in progress il giorno 06/03
incontro con committenza effettuato, test in corso
Risolte problematiche riscontrate', 'da chiudere test', '2024-12-31', '2025-06-30', '2025-06-09', '2025-06-09', '2025 Q2', false, 'L''implementazione è stata rivisitata più volte e rilavorata senza aprire nuova issue', '61-100', '50+') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-093', 'AWP', NULL, 'Cruscotto AWP', 'Modifica report A105 Cruscotto AWP', 'Media', 'Done', 'AWP-2054', 'Jira', 'IT', 'Manuela Graziani', 'ADI', NULL, NULL, '2025-06-30', NULL, '2025-06-06', '2025-06-06', '2025 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-094', 'AWP', NULL, 'Jira', 'Creazione sezione dedicata emergenze operative', 'Media', 'Cancelled', 'AWP-2055', 'Jira', 'IT', NULL, 'Demand', 'Creata chat su teams con solo i nostri ed alessandra (manuela fabrizio andrea) con nome Richieste Urgenti AWP', NULL, '2025-06-30', NULL, NULL, NULL, 'TBD', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-095', 'AWP', NULL, 'Modello DWH AWP - aggiornamento campo "Cluster AWP" con Distante S.R.L.', '-', 'Media', 'Done', 'AWP-2069', 'Jira', 'IT', NULL, NULL, NULL, NULL, '2025-06-03', NULL, '2025-06-03', '2025-06-03', '2025 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-096', 'AWP', NULL, 'Blocco / Sblocco programmato (Fase 2)', '-', 'Media', 'Done', 'AWP-2083', 'Jira', 'IT', 'Manuela Graziani', NULL, 'rilasciato al collaudo il 22 agosto', 'chiudere UAT', '2025-07-15', NULL, '2025-08-01', '2025-08-01', '2025 Q3', false, 'Gestita a best effort', '11-20', '6-15') on conflict (id_progetto) do nothing;
