insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-193', 'VLT', NULL, 'GMT VLT_Richiesta introduzione nuova regola MANUTENTORE_WMG in sale ADRIA', '-', 'Media', 'Done', 'VLT-546', 'Jira', 'IT', NULL, 'IT', 'Chiusa', NULL, '2026-01-26', NULL, '2026-01-26', '2026-01-26', '2026 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-194', 'VLT', NULL, 'Elenco Sale bloccate Gamenet e Lottomatica', NULL, 'Alta', 'Analysis', 'VLT-622', 'Jira', 'BU', 'Lorenzo Bontempi', 'IT', NULL, NULL, '2026-09-30', NULL, NULL, NULL, '2026 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-195', 'VLT', '{"Cruscotto VLT"}', 'Cruscotto', 'GMT_Richiesta creazione nuovi cluster VLT Novomatic per modelli FV330C (DIAMOND) e FV330D (X-DREAM)', 'Media', 'Done', 'VLT-575', 'Jira', 'IT/BU', 'Manuela Graziani', 'IT', 'Contratti - Chiusi Test GMNT e rilascio in prod', 'Estendere a LVR', '2026-03-31', '2026-04-10', '2026-04-10', NULL, '2026 Q2', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-196', 'VLT', '{"Cruscotto VLT"}', 'GMT VLT_Intergrazione e clusterizzazione perimetro ADRIA su cruscotto VLT', 'Modifiche al FE per la gestione dei nuovi modelli', 'Media', 'Done', 'VLT-554', 'Jira', 'IT', 'Manuela Graziani', 'IT', 'Chiusi sviluppi', 'Rilasciata in produzione', '2026-03-31', NULL, '2026-04-03', NULL, '2026 Q1', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-197', 'VLT', '{"Cruscotto VLT"}', 'Implementazione Report R13 FV637', 'Modifiche al FE per la gestione dei nuovi modelli', 'Media', 'Done', 'VLT-551', 'Jira', 'IT', 'Manuela Graziani', 'IT', 'Chiusi sviluppi', 'Da collaudare', '2026-03-31', '2026-04-10', '2026-04-10', NULL, '2026 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-198', 'VLT', '{"MGM"}', 'VLT - Bug Novomatic per ora legale', 'Procedura di inserimento massivo rettifiche Paid e gestione puntuale rettifiche IN', 'Media', 'Done', 'VLT-590', 'Jira', 'IT', 'Manuela Graziani', 'Amm.e', 'Rettifiche elaborate e contabilizzate', 'Esposizione sugli EC in data 30/4, da verificare', '2026-04-24', NULL, NULL, NULL, '2026 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-199', 'VLT', '{"Cruscotto VLT"}', 'LVR_Richiesta modifica controllo automatico 600 con BET>0 per sale senza data di collaudo', 'Estendere l''attuale controllo sui 600 giornalieri delle sale senza data di collaudo, che al momento analizza il solo campo BET, anche al campo IN e OUT. L''obiettivo è intercettare tutti i casi in cui la sala si trovi ad iniziare la raccolta con campi progressivi del 600 >0, sia in caso di BET>0, sia in caso di BET=0.', 'Media', 'Done', 'VLT-588', 'Jira', 'IT/BU', 'Manuela Graziani', 'IT', '-', 'Chiudere sviluppi e test per rilascio in prod settimana ventura', '2026-05-06', NULL, NULL, NULL, '2026 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-200', 'VLT', '{"Sikuli"}', 'Revisione schema progettuale Sikuli-ptf Novomatic', 'Per rispondere a urgenze di carattere commerciale, abbiamo necessità di adeguare l''attuale architettura dei progetti Sikuli alla modalità di lavorazione imposta dalla piattaforma per i nuovi modelli VLT FV637, FV330D, FV330C.

Il progetto di partenza dovrebbe poter essere alimentato all''occorrenza attraverso l''inserimento delle singole VLT e non costruito su un cluster predefinito a monte in fase di creazione del progetto.

Per rispettare il processo operativo previsto, avremmo bisogno di creare 8 progetti padre-figlio a cascata, così strutturati:

2026/05_Cabinet HD Cobra parte_1
2026/05_Cabinet HD Cobra parte_2
2026/05_Cabinet HD Cobra parte_3
2026/05_Cabinet HD Cobra parte_4
2026/05_Cabinet HD Cobra parte_5
2026/05_Cabinet HD Cobra parte_6
2026/05_Cabinet HD Cobra parte_7
PRODOTTO SPECIFICO DEL CLUSTER DI APPARTENENZA in modalità REPLECE
I progetti 1 e 2 eseguono il download/installazione del prodotto in modalità INSTALL/ENABLE. I progetti da 3 a 7 eseguono il SOLO DOWNLOAD del prodotto assegnato. Il progetto 8 applica il prodotto specifico del cluster (associato alla configurazione), in modalità REPLACE', 'Media', 'Done', 'VLT-607', 'Jira', 'BU', 'Manuela Graziani', 'IT', 'Il grosso dell''implementazione è stato rilasciato alla committenza in data 29/5
''Sviluppi su utlima funzionalità di caricamento puntuale conclusi. Rilascio anche su LVR effettuato', NULL, '2026-06-05', '2026-06-19', NULL, NULL, '2026 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-201', 'VLT', '{"Cruscotto VLT","Sikuli"}', 'GMT-LVR_Sviluppo funzionalità creazione progetti nuovi cluster VLT Novomatic ', 'sviluppo della funzionalità di creazione dei progetti Sikuli anche sui nuovi cluster VLT Novomatic, sul modello dello schema di creazione del progetto Sikuli implementata sui perimetri già esistenti:
 * LVR: cluster FV330C (DIAMOND) e FV330D (X-DREAM)
 * GMT: cluster FV330C (DIAMOND), FV330D (X-DREAM), ADRIA', 'Media', 'Done', 'VLT-592', 'Jira', 'BU', NULL, 'IT', 'Implementazione conclusa, verificata e pronta al rialscio in prod
Finalizzato rilascio per ambedue i concessionari', NULL, '2026-06-30', '2026-06-19', NULL, NULL, '2026 Q2', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-202', 'VLT', '{"Cruscotto VLT"}', 'GMT-LVR_Richiesta creazione cluster ARES modello IRIS', '-', 'Media', 'Done', 'VLT-586', 'Jira', 'IT', 'Manuela Graziani', 'IT', 'Sviluppo chiuso e condiviso con committenza', NULL, '2026-06-30', '2026-04-16', '2026-04-16', NULL, '2026 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-203', 'VLT', NULL, 'Interfaccia Bonus', 'GUI per Bonus VLT', 'Media', 'Done', 'VLT-459', 'Jira', 'BU', 'Lorenzo Bontempi', 'IT', 'Live', NULL, '2025-11-28', NULL, '2025-12-11', '2025-12-11', '2025 Q4', false, NULL, '21-60', '31-50') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-204', 'VLT', NULL, 'BI – Creazione interfaccia di gestione Modelli VLT ', 'Integrazione sul Modello', 'Media', 'Done', 'REP-392', 'Jira', 'IT', NULL, 'DP', 'Risolto problema su Utenza BIreader', 'Verifica in prod', '2025-11-14', '2025-11-24', '2025-11-26', '2025-11-26', '2025 Q4', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-205', 'VLT', '{"GAP"}', 'Modifica al motore dei bonus VLT', '"Sbarramento" su singolo Modello', 'Media', 'Done', 'VLT-568', 'Jira', 'BU', 'Nello, Lorenzo Bontempi', 'IT', 'Condivisa prima bozza
Sviluppi già in corso con configurabilità dei 180gg
Fatto incontro con committenza 17/02', 'Rilasciare in prod
', '2026-03-06', '2026-03-10', '2026-03-12', '2026-03-12', '2026 Q1', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-206', 'VLT', '{"MGM"}', 'Modifica al motore dei bonus VLT', 'Campo Tipo Aggregazione', 'Media', 'Done', 'VLT-570', 'Jira', 'IT', 'Nello, Lorenzo Bontempi', 'IT', NULL, 'Rilasciare in prod con pacchetto cumulativo ad ok definitivo collaudo', '2026-03-06', '2026-03-10', '2023-03-23', '2023-03-23', '2026 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-207', 'VLT', '{"DWH"}', 'Report unico Anagrafico Improvement', 'Modifiche al RUA Fase1', 'Media', 'Done', 'VLT-463
REP-486', 'Jira', 'IT/BU', NULL, 'DP', 'Collaudo effettuato in data 02/04 con esito positivo', 'Da rilasciare in produzione', '2026-03-13', '2026-03-30', NULL, NULL, '2026 Q1', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-208', 'VLT', '{"DWH"}', 'Report unico Anagrafico Sezione Macchine', 'Introduzione Modelli nel RUA Fase1', 'Media', 'Done', 'VLT-463
REP-487', 'Jira', 'IT/BU', NULL, 'DP', 'Collaudo effettuato in data 02/04 con esito positivo', 'Da rilasciare in produzione', '2026-03-13', '2026-03-30', NULL, NULL, '2026 Q1', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-209', 'VLT', '{"SAP","GAP"}', 'Gestione addendum VLT con rateo mensile (Fase2)', '-', 'Media', 'On Hold', 'VLT-572', 'Jira', 'IT/BU', 'Manuela Graziani', 'IT', '-', '-', NULL, NULL, NULL, NULL, 'TBD', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-210', 'VLT', NULL, 'Portale MGM - CMS', 'Caricamento massivo per Partita IVA ', 'Media', 'Done', 'VLT-449', 'Jira', 'IT', 'Lorenzo Bontempi', 'IT', NULL, NULL, '2025-07-30', NULL, '2025-07-28', '2025-07-28', '2025 Q3', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-211', 'VLT', NULL, 'MGM - Creazione funzioni VLT Non Operative e Ticket Manutentore VLT', 'Porting e ristrutturazione funzioni VLT Non Operative e Report Manutentori VLT da Cruscotto VLT su MGM', 'Media', 'Done', 'VLT-481', 'Jira', 'IT', 'Lorenzo Bontempi', 'IT', 'Live', NULL, '2025-12-30', NULL, '2025-09-22', '2025-09-22', '2025 Q4', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-212', 'VLT', NULL, 'MGM - Creazione storico VLT Non Operative', 'Aggiunta informazione storica vlt non operative a una certa data', 'Media', 'Done', 'VLT-491', 'Jira', 'IT', 'Lorenzo Bontempi', 'IT', 'in corso', 'obiettivo rilascio insieme a parte bimestrale entro fine mese', '2025-11-07', NULL, '2025-11-05', '2025-11-05', '2025 Q4', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-213', 'VLT', NULL, 'Automatismo versamenti preu AAMS', '-', 'Media', 'Done', 'VLT-482', 'Jira', 'IT', 'Lorenzo Bontempi, Manuela Graziani', 'IT', 'sviluppi terminati lato MGM. Va insieme alla parte AWP', 'Rilascio in UAT', '2025-10-31', NULL, '2025-10-23', '2025-10-23', '2025 Q4', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-214', 'VLT', NULL, 'VLT- Imlementazione nuovi campi su REP-197 (report periodico elenco completo sale Gaming con ID Betting)', '-', 'Media', 'Done', 'REP-246', 'Jira', 'BU', NULL, 'BU', NULL, NULL, '2025-06-17', NULL, '2025-09-17', '2025-09-17', '2025 Q2', false, 'il discorso si è prolungato a causa dell''uat molto lungo dovuto a rimpalli con la BU', '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-215', 'VLT', NULL, 'VLT- Modifica filtri Report periodico elenco completo sale Gaming con ID Betting', '-', 'Media', 'Done', 'REP-303', 'Jira', 'BU', NULL, 'BU', NULL, NULL, '2025-07-17', NULL, '2025-09-17', '2025-09-17', '2025 Q3', true, 'il discorso si è prolungato a causa dell''uat molto lungo dovuto a rimpalli con la BU', '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-216', 'VLT', NULL, 'Modifica report provider LVR aggiornamento % VLT VOLTA', '-', 'Media', 'Done', 'VLT-498', 'Jira', 'BU', NULL, 'IT', 'Attività che si prevede conclusa nella prima settimana di novembre', NULL, '2025-11-03', NULL, '2025-11-03', '2025-11-03', '2025 Q4', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-217', 'VLT', NULL, 'Interfaccia Bonus IT', 'Automazione import dati bonus', 'Media', 'Cancelled', 'VLT-406', 'Jira', 'IT', 'Nello', 'IT', '-', 'valutare se comunque necessaria staccata da interfaccia utente o se da fare congiuntamente a quella', '2025-09-30', NULL, NULL, NULL, '2025 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-218', 'VLT', NULL, 'Aggiunta Nuova Colonna nei Report R45', '# tkt aperti dopo ultima bettata', 'Media', 'Done', 'VLT-539', 'Jira', 'BU', NULL, 'IT', 'Sviluppo completato', 'rilascio in Collaudo in finalizzazione', '2026-01-30', NULL, '2026-02-02', '2026-02-02', '2026 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-219', 'VLT', NULL, 'PowerBI - Dashboard per analisi del contesto 1', '-', 'Media', 'Done', 'REP-359', 'Jira', 'BU', NULL, 'IT', 'mandata mail a curci
risposta di curci arrivata
Augusto ha risposto, abbiamo incassato ok per fase 1', NULL, '2025-10-08', '2025-10-31', '2025-11-21', '2025-11-21', '2025 Q4', false, 'Elapsed allungato per modifiche lato committenza', '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-220', 'VLT', NULL, 'PowerBI - Dashboard per analisi del contesto 2', '-', 'Media', 'Done', 'REP-360', 'Jira', 'BU', NULL, 'IT', 'Rilascio in collaudo', NULL, '2025-12-31', '2025-12-01', '2025-12-15', '2025-12-15', '2025 Q4', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-221', 'VLT', NULL, 'Modifica etichetta Sezione Documentazione Portale LGP', '-', 'Media', 'Done', 'VLT-536', 'Jira', 'BU', NULL, 'IT', NULL, NULL, '2026-03-31', NULL, '2026-01-27', '2026-01-27', '2026 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-222', 'VLT', NULL, 'PowerBI - Dashboard per analisi del contesto 3', '-', 'Media', 'Done', 'REP-361', 'Jira', 'BU', NULL, 'IT', 'Comunicato esito positivo al collaudo in data 17/02.', 'Perfizionare rilascio in Prod', '2025-12-30', '2026-02-20', NULL, NULL, '2026 Q1', false, 'Shift di consegna in attesa di ultime indicazioni dalla committenza', '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-223', 'VLT', '{"MGM"}', 'RUA Fase 2 - Funzione import per aggiornamento dei nuovi dati', NULL, 'Media', 'More Info', 'VLT-611', 'Jira', 'BU', 'Lorenzo Bontempi, Manuela Graziani', 'IT', NULL, 'Inserito tracciato di import, consolidato con BU
In corso sviluppi. Predisposizione procedura del file di caricamento entro fine settimana prossima.
Entro 3/7 chiedere alla committenza i dati da caricare al t0 (sentire E. Salomone). ', '2026-06-30', '2026-07-31', NULL, NULL, '2026 Q3', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-224', 'VLT', '{"DWH"}', 'PowerBI - Dashboard per analisi del contesto 4', '-', 'Media', 'Done', 'REP-362', 'Jira', 'BU', NULL, 'BU', 'Sentito Daisy il 03/04 per estendere orizzonte delle viste dei ticket vincenti e dei metodi di pagamento gli ultimi 2 anni. Previsto rilascio entro 7/04.
Fissato incontro interno il 28/04
Dare feedback a committenza sulle migliorie richieste. In particolare, su cosa possiamo portare e cosa dovrà essere integrato in una nuova cr -> + gestione univocità id ticket
Inviata mail a Curci il 28/04. In attesa completamento nuove modifiche e rilascio in prod.', 'chiuduere modifiche e rilasciare nuova versione', '2026-03-31', '2026-04-08', NULL, NULL, '2026 Q2', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-225', 'VLT', '{"DWH"}', 'Configurazione campo "Data installazione" e nuovo Report "Data inizio Bet"', 'implementazione di n. 2 campi sul modello BI:
1) campo "data installazione": individua la data di installazione delle VLT a prescindere dal BET. Precisamente l''utente deve avere la possibilità di selezionare una data o un range di date e il modello deve individuare tutte le VLT installate nel periodo/giorno selezionato. L''output deve essere per CIV e non per numero assoluto.

2) campo "data inizio BET" :  partendo da una lista di VLT (CIV) l''utente deve avere la possibilità di visualizzare la data di inizio raccolta di ogni VLT (per inizio raccolta si intende primo giorno di BET > 0).', 'Media', 'UAT', 'VLT-594
REP-605', 'Jira', 'BU', 'Manuela Graziani', 'DP', 'Avallata dal gruppo richiedente la soluzione proposta basata su:
- configurazione della data di installazione come misura dinamica per restituire la data minima di installazione per la quale la VLT risulta associata alla sala;
- creazione report con range di filtri di data inizio e data fine insistenti sulla data di installazione per monitorare spostamenti di civ nelle sale e inizio del rendicontato (data inizio bet >0)', 'Collaudo Report in corso, da chiudere
Da avviare collaudo sulla modifica al modello a valle delle attività, in corso, di preparazione/allineamento del modello stesso in BS', '2026-07-06', NULL, NULL, NULL, '2026 Q3', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-226', 'VLT', NULL, 'MGM – Creazione interfaccia di gestione Modelli VLT ', '-', 'Media', 'Done', 'VLT-467', 'Jira', 'IT', 'Lorenzo Bontempi', 'IT', 'in corso', NULL, '2025-08-31', NULL, '2025-08-21', '2025-08-21', '2025 Q3', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-227', 'VLT', NULL, 'MGM - Censimento costo rete Gestore NS VLT', '-', 'Media', 'Done', 'VLT-494', 'Jira', 'IT', 'Lorenzo Bontempi', 'IT', 'Stabilito che la lavorazione di qst Issue conviene vada con quella su IF Bonus VLT', 'chiudere sviluppo e da rilasciare con i bimestrali', '2025-12-30', '2025-11-06', '2025-11-06', '2025-11-06', '2025 Q4', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-228', 'VLT', '{"DWH","Se-Gag"}', 'RUA Fase 2', 'Inserimento nuove informazioni contrattuali a Sistema ', 'Media', 'More Info', 'VLT-183', 'Jira', 'CSE + BU', 'Lorenzo Bontempi, Manuela Graziani', 'BU', 'In attesa di fb dalla committenza (Radicioni, Monaci, Salvati) per restituzione file con il tracciato e i campi di pertinenza di ogni gruppo. In corso incontri per ricezione campi anagrafici sala quando la sala non è ancora attiva
In corso analisi del file restituito dalla committenza', 'Organizzare call con Giovanna. Al momento on hold per mancanza del dato, una volta ricevuti i dati sarà possibile riprendere le attività lato DP. Aggiornati i dati sulle tabelle
In attesa di feedback da parte della committenza', '2026-07-16', NULL, NULL, NULL, '2026 Q3', false, NULL, '61-100', '50+') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-229', 'VLT', NULL, 'GMT VLT_Richiesta introduzione nuova regola MANUTENTORE_Modello FV637NLX', '-', 'Media', 'Done', 'VLT-528', 'Jira', 'IT', 'Manuela Graziani', 'IT', 'nuovo', NULL, '2025-11-19', NULL, '2025-11-19', '2025-11-19', '2025 Q4', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-230', 'VLT', NULL, 'Classificazione COMMERCIALE Modelli VLT AdM', '-', 'Media', 'Done', 'VLT-461', 'Jira', 'IT', 'Manuela Graziani', 'IT', 'i modelli ritenuti orfani non sono di conoscenza del business --> verranno ignorati', 'necessario "tirare dentro" la query del DWH e verificare le informazioni ottenute', '2025-07-30', NULL, '2025-08-21', '2025-08-21', '2025 Q3', false, 'Dovuto a revisioni e ripensamenti della committenza', '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-231', 'VLT', NULL, 'Automazione Master Reset Spielo via Click and care', '-', 'Media', 'Done', 'BSS-320', 'Jira', 'IT', NULL, 'Agesoft - TIBCO', 'RU consolidato.
''Sikuli chiuso metà ottobre per GMNT e LVR
completata struttura tabella di interfaccia via tibco
in attesa di fb da lato agecom - tibco
Riattivato
in attesa info da Cruciani', 'Chiudere BS
in verifica timer 30 min per scodamento sikuli', '2025-05-30', '2025-07-15', '2025-07-15', '2025-07-15', '2025 Q3', true, 'Ritardi accumulati per successivi rework su evidenze da test', '21-60', '31-50') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-232', 'VLT', NULL, 'MGM portale contratti ', 'Aggiunta Rettifiche di tipo ''Cambio contrattuale retroattivo'' su workflow autorizzativo ', 'Media', 'Done', 'OT-878', 'Jira', 'IT', 'Nello, Lorenzo Bontempi', 'GM-DEV', 'Live', NULL, '2025-07-30', NULL, '2025-08-21', '2025-08-21', '2025 Q3', false, 'Gestita a best effort', '21-60', '31-50') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-233', 'VLT', NULL, 'Rettifiche', 'Risoluzione problematiche su LVR', 'Media', 'Done', 'VLT-556', 'Jira', 'BU', 'Lorenzo Bontempi', '-', 'Go-live 17/02', 'Chiusura analisi e disegno soluzione
Sviluppi in corso
', '2026-03-31', '2026-02-17', NULL, NULL, '2026 Q1', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-234', 'VLT', NULL, 'VLT- Update Report periodico elenco completo sale Gaming con ID Betting', '-', 'Media', 'Done', 'REP-197', 'Jira', 'BU', NULL, 'DWH', NULL, 'in chiusura', '2025-05-30', '2025-06-03', '2025-06-03', '2025-06-03', '2025 Q2', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-235', 'VLT', NULL, 'Master Unico Anagrafico - Recupero e Storicizzazione dell''ultimo codice EA valido (REP.158)', '-', 'Media', 'Done', 'VLT-410', 'Jira', 'IT', NULL, 'DWH', 'in produzione', NULL, '2025-05-30', NULL, '2025-04-29', '2025-04-29', '2025 Q2', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-236', 'VLT', NULL, 'Adeguamento tabella per CashCall', 'Adeguamento ad LVR tabella di alimentazione CashCall', 'Media', 'Done', 'OT-834', 'Jira', 'IT', NULL, 'ADI + Dev', 'Live', NULL, '2024-12-31', '2025-05-16', '2025-05-16', '2025-05-16', '2025 Q2', false, 'Attività a bassa priorità lavorata a best effort', '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-237', 'VLT', NULL, 'Disallineamento tra cassetto netto e somma corrispettivi filiera', '-', 'Media', 'Done', 'VLT-412', 'Jira', 'IT', NULL, 'DWH', 'Stabiliti i razionali per rivedere la query del rendicontato per adeguarla alla nuova logica
in rilascio', NULL, '2025-06-30', NULL, '2025-06-11', '2025-06-11', '2025 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-238', 'VLT', NULL, 'MGM - Porting Report 39 e funzione Blocco/Sblocco Sale VLT', '-', 'Media', 'Done', 'OT-921', 'Jira', 'IT', NULL, 'GM-DEV', 'in corso', 'In attesa abilitazione agli utenti', '2025-03-31', '2025-04-07', '2025-04-07', '2025-04-07', '2025 Q2', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-239', 'VLT', NULL, 'MODIFICHE CRUSCOTTO DIREZIONALE VLT - REPORT R11 - CONTRATTI VLT ', '-', 'Media', 'Done', 'VLT-396', 'Jira', 'IT', 'Manuela Graziani', 'IT', 'LIVE', NULL, '2025-03-31', NULL, '2025-03-31', '2025-03-31', '2025 Q1', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-240', 'VLT', NULL, 'Richiesta creazione cluster FV637 NLX GMT', '-', 'Media', 'Done', 'VLT-344', 'Jira', 'IT', NULL, 'ADI', 'effettuato passaggio con botta, loro devono fare un passaggio con monaci per capire se ci sono contratti che dicono ciò', NULL, '2024-12-31', NULL, '2024-12-03', '2024-12-03', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
