insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-289', 'AWP', NULL, 'Cruscotto AWP', 'richiesta storico  report RR24  Cruscotto GMT e LVR', 'Bassa', 'Done', 'AWP-1508', 'Jira', 'IT', NULL, 'ADI', 'messo in resolved dalla committenza il 13/01', '-', '2024-12-31', NULL, '2025-01-13', '2025-01-13', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-290', 'AWP', NULL, 'Allineamento "Tipologia esercizio" con Albo', '-', 'Bassa', 'Done', 'AWP-660', 'Jira', 'IT', NULL, 'DWH', 'LIVE', '-', '2024-05-06', NULL, '2024-05-06', '2024-05-06', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-291', 'AWP', NULL, 'Modello AWP ', 'aggiunta calcolo su n. AWP giocanti', 'Bassa', 'Done', 'OT-505', 'Jira', 'IT', NULL, 'IT', 'LIVE', '-', '2024-05-02', NULL, '2024-05-02', '2024-05-02', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-292', 'AWP', NULL, 'Cruscotto AWP', 'AWP Bloccate in magazzino “Report R024” – lato GMT/LVR ', 'Bassa', 'Done', 'AWP-871', 'Jira', 'IT', NULL, '-', 'LIVE', '-', '2024-05-10', NULL, '2024-05-10', '2024-05-10', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-293', 'AWP', NULL, 'MGM', 'Cessazione account portali GMT e LVR', 'Bassa', 'Done', 'AWP-1418', 'Jira', 'IT', NULL, 'GM-DEV', 'Da prod. Release a Last Done', '-', '2024-10-14', NULL, '2024-10-14', '2024-10-14', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-294', 'AWP', NULL, 'Cruscotto AWP', 'Codice sede “Report A019 – Report blocchi slot” storico GMT/LVR', 'Bassa', 'Done', 'AWP-870', 'Jira', 'IT', NULL, '-', 'LIVE', '-', '2024-05-10', NULL, '2024-05-10', '2024-05-10', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-295', 'AWP', NULL, 'Cruscotto AWP', 'Implementazione di una scheda per la consultazione dei blocchi delle awp con ricerca per ragione sociale e per codice sede', 'Bassa', 'Done', 'AWP-358', 'Jira', 'IT', NULL, 'ADI', 'Live', NULL, '2024-07-09', NULL, '2024-07-09', '2024-07-09', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-296', 'AWP', NULL, 'LGP', 'Implementazioni per flusso gestione Invio e Reso PDA', 'Bassa', 'Done', 'CCLO-158', 'Jira', 'IT', NULL, 'GM-Dev + SAP-CRM + Tibco', 'LIVE', 'chiudere verifiche ed implementazioni lato tibco/network
test interno
il requisito sarà integrato con una ulteriore implementazione presente in successiva CR che prevede il passaggio del documento DDT da CRM a SAP ECC per visibilità struttura lato magazzino', '2024-07-18', NULL, '2024-07-18', '2024-07-18', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-297', 'AWP', NULL, 'Cruscotto AWP', 'Modifica cruscotto report R0218', 'Bassa', 'Done', 'AWP-360', 'Jira', 'IT', NULL, 'ADI', 'Live', NULL, '2024-05-31', NULL, '2024-05-31', '2024-05-31', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-298', 'AWP', NULL, 'Cruscotto AWP', 'Richiesta report AWP fuori SLA oltre 30 giorni riepilogo annuo ', 'Bassa', 'Done', 'AWP-297', 'Jira', 'IT', NULL, 'ADI', 'Live', NULL, '2024-06-06', NULL, '2024-06-06', '2024-06-06', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-299', 'AWP', NULL, 'Richiesta invio mail di avviso 724 lato GMT e LVR', '-', 'Bassa', 'Done', 'AWP-2315', 'Jira', 'IT', NULL, 'ADI', 'in corso', NULL, '2025-12-30', NULL, '2025-09-22', '2025-09-22', '2025 Q4', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-300', 'AWP', '{"DWH","SAP"}', 'Forfait tombale su sale con esercente scassettatore (LVR)', '-', 'Bassa', 'Done', 'AWP-2471', 'Jira', 'IT', 'Lorenzo Bontempi', 'IT', 'Sviluppi conclusi al netto del TO DO', 'Mancano porzione reportistica su Cruscotto AWP ed adeguamento quote su Cruscotto PREU, motivo per il quale l''attività rimane aperta
Stabilita apertura di un altro', '2026-02-15', '2026-02-17', NULL, NULL, '2026 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-301', 'AWP', '{"CRUSCOTTO AWP"}', 'Cruscotto AWP', 'Report A019 - Report blocchi slot | inserimento nuove colonne', 'Bassa', 'Done', 'AWP-2440', 'Jira', 'IT', 'Manuela Graziani', 'IT', 'Rilasciata una prima versione in verifica
Ultime modifiche rilasciate in data 14/5', 'In corso completamento delle ultime modifiche richieste. Prossime richieste andranno necessariamente gestite con nuove CR', '2026-04-15', '2026-06-30', '2026-07-07', NULL, '2026 Q2', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-302', 'CROSS', NULL, 'LGP', 'LGP improvement post Nuovo CMS', 'Bassa', 'Done', 'VLT-296', 'Jira', 'BU', 'Lorenzo Bontempi', 'BU', 'in corso sviluppi ', NULL, '2025-06-30', '2025-07-15', '2025-07-01', '2025-07-01', '2025 Q3', false, NULL, '21-60', '31-50') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-303', 'CROSS', '{"MGM"}', 'Dashboard MGM per Visite Ispettive', 'Creazione Dashboard per monitoraggio su ambi i Concessionari dello stato di avanzamento delle visite ispettive ai pdv nei simestri in corso e nell''anno', 'Bassa', 'To Start', 'VLT-601', 'Jira', 'BU', 'Lorenzo Bontempi', 'IT', 'Sostenuto incontro con il richiedente per strutturazione del requisito', 'Pianificare l''attività', '2026-12-31', NULL, NULL, NULL, '2026 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-304', 'VLT', NULL, 'Cash Call TIR', 'Modifica Etichette e Modifica Box Finanziario per TIR GMT', 'Bassa', 'On Hold', 'VLT-283', 'Jira', 'BU', NULL, 'BU', 'Revisione RU da parte di committenza', 'in attesa revisione
Valutare eliminazione o nuova analisi', NULL, NULL, NULL, NULL, 'TBD', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-305', 'VLT', NULL, 'MGM - Improvement - Classificazione COMMERCIALE Modelli VLT AdM', 'Aggiunta informazione provider per gestione modello commerciale e visualizzazione su modello tecnico', 'Bassa', 'Done', 'VLT-484', 'Jira', 'BU', 'Lorenzo Bontempi', 'Demand', 'Verificata effettiva necessità con la committenza', 'Da pianificare', '2026-03-30', NULL, '2025-10-23', '2025-10-23', '2026 Q1', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-306', 'VLT', '{"DWH"}', 'DWH', 'Nuovi Campi Modello VLT - Distribuzione giocate per singolo Gioco', 'Bassa', 'On Hold', 'REP-91', 'Jira', 'BU', NULL, 'Demand + ADI', '-', '-', NULL, NULL, NULL, NULL, 'TBD', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-307', 'VLT', NULL, 'Cruscotto VLT', 'Sviluppo scheda configurazione giochi cluster WMG-ARES', 'Bassa', 'Done', 'VLT-360', 'Jira', 'IT', NULL, 'IT', 'chiuso', NULL, '2024-12-31', NULL, '2025-02-25', '2025-02-25', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-308', 'VLT', NULL, 'Cruscotto VLT', 'Modifca delle installazioni giochi lato SPIELO con annullamento dei processi "sospesi"', 'Bassa', 'Done', 'VLT-389', 'Jira', 'IT', NULL, 'IT', NULL, NULL, '2024-12-31', NULL, '2025-02-19', '2025-02-19', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-309', 'VLT', NULL, 'DWH', 'Introduzione nuovi campi sul Modello per CIV - solo WIN TAX', 'Bassa', 'Done', 'VLT-55', 'Jira', 'BU', NULL, 'Demand + ADI', 'rilasciato win tax', NULL, '2024-12-31', NULL, '2025-01-21', '2025-01-21', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-310', 'VLT', NULL, 'Data Platform', 'Elaborazioni per sostituzione Grafana', 'Bassa', 'Done', 'REP-159', 'Jira', 'IT', NULL, 'DWH', 'perfezionata apertura rotte
''in lavorazione', 'chiudere implementazione', '2025-04-30', NULL, '2025-04-24', '2025-04-24', '2025 Q2', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-311', 'VLT', NULL, 'Modello VLT', 'cambio etichetta Eos-Ares', 'Bassa', 'Done', 'REP-160', 'Jira', 'IT', NULL, 'DWH', NULL, 'confronto con committenza', '2025-03-31', NULL, '2025-03-26', '2025-03-26', '2025 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-312', 'VLT', NULL, 'BigEasy', 'Adeguamenti per Esercenti scassettatori anche se non TIR', 'Bassa', 'Done', 'VLT-231', 'Jira', 'BU', NULL, 'GM-Dev', 'Effettuata call con Business in data 26/02
Approvata soluzione di dare visibilità della sezione “FINANZIARIA” nella Cash Call ai soli GdS con TIR BigEasy.
Iniziare la lavorazione nel mentre della predisposizione ambiente di collaudo per manutentore e IV incaricato
Live il 28/03', NULL, '2024-03-28', NULL, '2024-03-28', '2024-03-28', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-313', 'VLT', NULL, 'CRUSCOTTO', 'Correzioni cruscotto direzionale R10_ Concessionario LVR', 'Bassa', 'Done', 'OTH-24', 'Jira', 'IT', NULL, 'ADI - BU', 'completata, effettuato test', '-', '2024-03-05', NULL, '2024-03-05', '2024-03-05', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-314', 'VLT', NULL, 'BigEasy', 'GM - Estrazione di una istantanea per associazioni TIR/PDV e TIR/SLOT (BIGEASY)', 'Bassa', 'Done', 'OT-454', 'Jira', 'BU', NULL, 'ADI', 'Creata issue su Jira 
A seguito di call con i colleghi di Big Easy si è deciso per la predisposizione di una estrazione raffigurante le associazioni TIR/PDV e TIR/SLOT secondo il tracciato di seguito (da configurare)', 'chiudere verifiche e condividere estrazione con la committenza', '2024-03-29', NULL, '2024-03-29', '2024-03-29', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-315', 'VLT', NULL, 'Fornitura flussi giocati/rendicontato Vs DWH ', 'Metodo di sincronizzazione', 'Bassa', 'Cancelled', NULL, 'Manuale', 'IT', NULL, 'ADI', 'Immaginata soluzione con "semaforo" sia per giocato che per rendicontato
WA: seconda schedulazione alle 13.30 implementata', 'Verifica su unificazione dei 2 flussi CS e SS', '2024-08-29', NULL, NULL, NULL, '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-316', 'VLT', NULL, 'LGP', 'Modifiche a sezione documentale Gioco Responsabile', 'Bassa', 'Done', 'VLT-276', 'Jira', 'BU', NULL, 'GM-Dev + online', 'test in collaudo in positivo', 'in attesa ok per abilitazioni profili', '2024-08-30', NULL, '2024-08-30', '2024-08-30', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-317', 'VLT', NULL, 'Cruscotto VLT', 'Richiesta Report con VLT non giocanti dopo 5 giorni dalla chiusura del ticket', 'Bassa', 'Done', 'VLT-199', 'Jira', 'IT', NULL, 'ADI', 'Feedback ricevuto, LIVE', NULL, '2024-02-13', NULL, '2024-02-13', '2024-02-13', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-318', 'AWP', NULL, 'Cruscotto AWP', 'DASHBOARD | AWP', 'Bassa', 'Done', 'AWP-2436', 'Jira', 'IT', 'Manuela Graziani', 'IT', 'Inviata al gruppo ADI in data 05/11
Lavorazione avviata
Chiusa e consegnata 09/02
Rilasciata 18/02', 'Segnalato bug e fixato in data 16/02.', '2026-01-31', '2026-02-17', NULL, NULL, '2026 Q1', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-319', 'AWP', NULL, 'Gestione Operativa', 'Mail di Alert per gestione contratti, subentri, associazioni e sospensioni', 'Bassa', 'Cancelled', NULL, 'Manuale', 'NS + BU', NULL, '-', 'richiesto da Amoia ', 'Da verificare cosa manca in tavolo dedicato', '2024-05-20', NULL, NULL, NULL, '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-320', 'CROSS', NULL, 'Reportistica Credito ', '-', 'Bassa', 'Cancelled', NULL, 'Manuale', 'Credito', NULL, '-', NULL, '-', '2024-11-18', NULL, NULL, NULL, '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-321', 'CROSS', NULL, 'Reportistica Credito ', '-', 'Bassa', 'Cancelled', NULL, 'Manuale', 'Credito', NULL, '-', NULL, '-', '2024-11-19', NULL, NULL, NULL, '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-322', 'AWP', NULL, 'Associazione mandatario sale dirette LVR con concessionario a residuo', '-', NULL, 'Done', 'AWP-1802', 'Jira', 'BU', 'Nello, Lorenzo Bontempi, Manuela Graziani', 'GM-DEV', 'Iniziati incontri di analisi tecnica, convertire in CR mettere sistemi impattiti in GAP, MGM e sistemi AWP
interventi sostanzialmente completati al netto di quelli lato AP
in DEV lato AP
due binari nella forma di rendicontazione e anche DB
Start Test intergrato lato web
Test sul massivo positivo
Rilascio il 10/06', 'Chiudere interventi lato AP; 
test della matematica su previsione entro settimana corrente
inserimento del contratto in produzione', '2025-06-30', NULL, '2025-06-10', '2025-06-10', '2025 Q2', false, '[Priorità originale: 1-2 — da rivedere manualmente]', '21-60', '31-50') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-323', 'VLT', NULL, 'Report Ascob', '-', NULL, 'Cancelled', NULL, 'Manuale', 'BU', NULL, '-', 'Attività ritirata in data 23/11', NULL, '2024-05-20', NULL, NULL, NULL, '2024 Q2', false, '[Priorità originale: ? — da rivedere manualmente]', NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-324', 'VLT', NULL, 'Cruscotto VLT', 'Implementazioni Dashboard VLT_5 - Implementazioni Area Statistiche', NULL, 'Done', 'VLT-134', 'Jira', 'IT', NULL, NULL, 'Creata issue su JIRA', 'Chiusura verifiche on field', '2024-01-15', NULL, '2024-01-15', '2024-01-15', '2024 Q1', false, '[Priorità originale: 5a — da rivedere manualmente]', NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-325', 'VLT', NULL, 'Cruscotto VLT', 'Implementazioni Dashboard VLT_6 - Ground Control: Implementazioni', NULL, 'Done', 'VLT-135', 'Jira', 'IT', NULL, NULL, 'Creata issue su JIRA', 'Chiusura verifiche on field', '2024-01-15', NULL, '2024-01-15', '2024-01-15', '2024 Q1', false, '[Priorità originale: 5b — da rivedere manualmente]', NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-326', 'CROSS', NULL, 'SAP', 'Introduzione multi cc per medesimo cliente', NULL, 'Cancelled', NULL, 'Manuale', 'BU VLT + Credito', NULL, '-', '-', '-', NULL, NULL, NULL, NULL, 'TBD', false, '[Priorità originale: IP — da rivedere manualmente]', NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-327', 'VLT', NULL, 'Fine tuning reportistica per prodotto', 'Contribuzione Jackpot e miglioramento reportistica per prodotto', NULL, 'Definition', NULL, 'Manuale', 'BU', NULL, '-', '-', '-', NULL, NULL, NULL, NULL, 'TBD', false, '[Priorità originale: IP — da rivedere manualmente]', NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-328', 'VLT', NULL, 'Stabilizzazione Compensi', 'Creare un nuovo modello di stabilizzazione dei compensi ai clienti (simil stabilizzatore attuale, ma per tutti con % fissa es. 85%), da applicare sia ad LVR sia a GMT (al minimo introduzione del motore Stabilizzazione/Aggio Negativo LVR per GMT)', NULL, 'Definition', NULL, 'Manuale', 'BU', NULL, '-', 'Iniziata la fase di interlocuzione e verifica per l’introduzione della tutela su Aggio Negativo', 'Tracciare l’esigenza e calarla nella realtà contabile GMNT', NULL, NULL, NULL, NULL, 'TBD', false, '[Priorità originale: IP — da rivedere manualmente]', NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-329', 'VLT', NULL, 'Pagamento Vincite >5K', 'Modifica processo per evitare che il cliente DEBBA recarsi a Roma o inviare Raccomandata: completamento pratica in Sala, pagamento a valle dei controlli di LTM su documenti inviati via Daisy e successiva archiviazione degli originali', NULL, 'Definition', NULL, 'Manuale', 'BU', NULL, '-', '-', '-', NULL, NULL, NULL, NULL, 'TBD', false, '[Priorità originale: IP — da rivedere manualmente]', NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-330', 'VLT', '{"LGP"}', 'LGP', 'modifiche al CMS', NULL, 'Definition', NULL, 'Manuale', 'BU', NULL, '-', 'item aggiunto durante SAL BU', '-', NULL, NULL, NULL, NULL, 'TBD', false, '[Priorità originale: IP — da rivedere manualmente]', NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-331', 'VLT', '{"LGP"}', 'LGP', 'Funzione LGP per rubrica Manutentori da mettere nel verbale', NULL, 'Definition', NULL, 'Manuale', 'BU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TBD', false, '[Priorità originale: IP — da rivedere manualmente]', NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-332', 'VLT', NULL, 'Manutentore LVR', 'Introduzione Manutentore su LVR', NULL, 'On Hold', NULL, 'Manuale', 'BU', NULL, '-', 'ambiente di collaudo predisposto, da censire attività', '-', NULL, NULL, NULL, NULL, 'TBD', false, '[Priorità originale: IP-1 — da rivedere manualmente]', NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-333', 'CROSS', NULL, 'Portale Contratti - contratto PDV', '-', NULL, 'Done', 'OT-603', 'Jira', 'IT', 'Lorenzo Bontempi', 'IT', 'Pianificazione condivisa
prossima al rilascio in collaudo la parte di gestione contratti VLT', 'chiudere test lato DB massiva AWP', '2024-12-31', '2025-02-20', '2025-02-20', '2025-02-20', '2025 Q1', false, 'Ritardo solo su pianificazione interna [Priorità originale: TOP — da rivedere manualmente]', '61-100', '50+') on conflict (id_progetto) do nothing;

