insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-145', 'AWP', NULL, 'GAP', 'Mail di conferma di fine ricalcolo', 'Media', 'Done', 'OT-575', 'Jira', 'IT', NULL, 'GM-DEV', 'Live
da dev a last done', '-', '2024-06-24', NULL, '2024-06-24', '2024-06-24', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-146', 'AWP', NULL, 'Cruscotto PREU', 'Marcatura controlli PREU giornalieri + Storicizzazione', 'Media', 'Done', 'AWP-759', 'Jira', 'IT', NULL, 'ADI', 'Live (su entrambe le concessionarie)', '-', '2024-09-23', NULL, '2024-09-23', '2024-09-23', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-147', 'AWP', NULL, 'Cruscotto PREU', 'Marcatura controlli PREU quindicine + Storicizzazione', 'Media', 'Done', 'OT-703', 'Jira', 'IT', NULL, 'ADI', 'Live', NULL, '2024-11-15', NULL, '2024-11-15', '2024-11-15', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-148', 'AWP', NULL, 'Cruscotto AWP', 'nuovo allarme disallineamento PDA/ubicazione (magazzino) lato GMT e LVR', 'Media', 'Done', 'AWP-1245', 'Jira', 'IT', NULL, 'GM-DEV', 'Live', '-', '2024-07-12', NULL, '2024-07-12', '2024-07-12', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-149', 'AWP', NULL, 'Cruscotto AWP', 'Nuovo allarme mail per disallineamento AWP/PDA Lato GMNT e LVR', 'Media', 'Done', 'AWP-590', 'Jira', 'IT', NULL, 'ADI', 'LIVE', NULL, '2024-06-17', NULL, '2024-06-17', '2024-06-17', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-150', 'AWP', NULL, 'Master Unico Anagrafico', 'Parco macchine Awp - Soluzione per tenere traccia delle macchine awp nei diversi stati di vita', 'Media', 'Done', 'AWP-594', 'Jira', 'IT', NULL, 'ADI', 'Emerse segnalazioni in fase di Collaudo
Allegato file su Jira in data 02/02/2024 in cui si verifica che le 144 awp mancanti sono effettivamente in stato "Sequestro"', '-', '2024-02-08', NULL, '2024-02-08', '2024-02-08', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-151', 'AWP', NULL, 'Cruscotto AWP', 'Perimetro "Report A019 - Report blocchi slot" storico GMT/LVR', 'Media', 'Done', 'AWP-1290', 'Jira', 'IT', NULL, 'ADI', 'Live', NULL, '2024-09-13', NULL, '2024-09-13', '2024-09-13', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-152', 'AWP', NULL, 'LGP', 'restituzione PDA via LGP - DDT su SAP ECC', 'Media', 'Done', 'AWP-1302', 'Jira', 'IT', NULL, 'SAPECC', 'Live', NULL, '2024-09-12', NULL, '2024-09-12', '2024-09-12', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-153', 'AWP', NULL, 'Invio mail PEO giornaliera lato GMT- LVR per SLA 4 gg', '-', 'Media', 'Done', 'AWP-2162', 'Jira', 'IT', NULL, NULL, 'Live', NULL, '2025-07-30', NULL, '2025-07-22', '2025-07-22', '2025 Q3', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-154', 'AWP', NULL, 'GM - AWP - GAP - Ricalcoli annuali', 'Ricalcoli straordinario su annuali', 'Media', 'Done', 'OT-460', 'Jira', 'IT', NULL, 'GM-Dev', 'Chiusa fase di test
Implementazioni del ricalcolo e del ribaltamento effettuato in modo disgiunto
ricevuta segnalazione da gestore
individuati da controlli interni set di AWP che necessitano di ricalcoli
Da UAT a LAST DONE', 'funzionalità attiva (anche ribaltamento) in attesa verifiche
in attesa eventuali file da ricarare (LGP)', '2024-05-08', NULL, '2024-05-08', '2024-05-08', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-155', 'AWP', NULL, 'LGP', 'Richiesta export-import strutture sinottici PDV per fase backoffice Mappatura PDV', 'Media', 'Done', 'OT-572', 'Jira', 'IT', NULL, 'GM-DEV', 'LIVE', '-', '2024-07-02', NULL, '2024-07-02', '2024-07-02', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-156', 'AWP', NULL, 'MGM', 'Rivalsa NOE', 'Media', 'Done', 'OT-644', 'Jira', 'IT', NULL, 'ADI', 'Da prod release a Last Done (produzione nascosta)', '-', '2024-10-14', NULL, '2024-10-14', '2024-10-14', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-157', 'AWP', NULL, 'AWP - SEGAG -  Ingegnerizzazione invio comunicazioni peo - lato Gmt - LVR ', 'Tema delle ricevute', 'Media', 'Done', 'OT-653', 'Jira', 'IT', NULL, 'ADI', 'continuazione della AWP-724
''1) Test ricezione ricevuta di una pec inviata (Done)

2) Ricerca ricevuta per oggetto, mittente e data (Done)', 'Creare repository per le ricevute', '2024-10-29', NULL, '2024-10-29', '2024-10-29', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-158', 'AWP', NULL, 'Aggiunta riferimenti AWP-PDV per AgeSoft - GESTORE ALLSTAR', '-', 'Media', 'Done', 'OT-475', 'Jira', 'IT', NULL, 'IT', 'LIVE il giorno 19/04', 'probabile fine in settimana', '2024-04-19', NULL, '2024-04-19', '2024-04-19', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-159', 'AWP', NULL, 'MGM - Ricerca Soggetto', '-', 'Media', 'Done', 'AWP-2373', 'Jira', NULL, NULL, 'IT', NULL, 'Pianificare', '2025-12-31', NULL, '2025-10-23', '2025-10-23', '2025 Q4', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-160', 'AWP', NULL, 'Cruscotto AWP', 'SE GAG | Inserimento date di validazione _ INACCESSIBILITA''', 'Media', 'Done', 'AWP-1974', 'Jira', 'IT', 'Manuela Graziani', 'ADI', 'Live', NULL, '2025-05-30', NULL, '2025-05-09', '2025-05-09', '2025 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-161', 'AWP', NULL, 'Cruscotto PREU AWP', 'Funzionalità correzione errori - acquisti altro concessionario e azzeramenti', 'Media', 'Done', 'OT-734', 'Jira', 'IT', NULL, 'GAP', 'specifiche condivise', 'Sviluppo da adeguare a chiamate online', '2024-12-31', NULL, '2025-02-28', '2025-02-28', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-162', 'AWP', NULL, 'GAP+MGM - Portale Contratti LVR- Richiesta nuova funzione Quota Concessionaria Condizionata', '-', 'Media', 'Done', 'AWP-2209', 'Jira', 'BU', 'Nello, Lorenzo Bontempi, Manuela Graziani', 'IT', 'Sviluppi terminati, Test effettuati
LIVE', 'In esecuzione collaudo con dati reali', '2026-03-31', '2026-02-23', NULL, NULL, '2026 Q1', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-163', 'AWP', NULL, 'MGM-Portale Contratti', 'Integrazione Flag Diretta su Massivo', 'Media', 'Done', 'AWP-2507', 'Jira', 'IT', 'Lorenzo Bontempi', 'IT', 'Rilascio in prod', NULL, '2025-12-31', '2026-01-15', '2026-01-13', '2026-01-13', '2026 Q1', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-164', 'AWP', NULL, 'Modello DWH AWP - budget', 'dashboard interne PBI, avremmo bisogno della disponibilità dei dati di budget', 'Media', 'Done', 'REP-357', 'Jira', 'IT', NULL, 'BU', '- chiesta autorizzazione a SOC per ambiente di sviluppo
- chiusa lavorazione CMFP-113332', NULL, '2025-10-24', '2025-11-26', '2025-11-26', '2025-11-26', '2025 Q4', false, 'In ritardo per tempi lunghi di security', '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-165', 'AWP', NULL, 'Richiesta inserimento  mandatario nel prospetto iniziale nel portale MGM', '-', 'Media', 'Done', 'AWP-2412', 'Jira', 'IT', NULL, 'IT', 'Rilasciato in collaudo', 'da rilasciare in prod il 5/11', '2025-12-30', '2025-11-05', '2025-11-05', '2025-11-05', '2025 Q4', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-166', 'AWP', NULL, 'Eliminazione di storni e ricalcoli "fittizi" dai rendiconti', '-', 'Media', 'Done', 'AWP-2325', 'Jira', 'IT', 'Nello', 'IT', 'in produzione', NULL, '2025-11-28', '2026-01-15', '2026-01-13', '2026-01-13', '2026 Q1', false, 'Emerse nuove casistiche non coperte durante i test', '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-167', 'AWP', '{"DB"}', 'PEC Assessment Utenze LGP – Integrazione dati richiesti GMT e LVR', NULL, 'Media', 'Done', 'AWP-2742', 'Jira', 'IT', 'Manuela Graziani', 'IT', NULL, 'Attività completata il 24/04.', '2026-04-24', NULL, NULL, NULL, '2026 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-168', 'AWP', '{"SAP","TIBCO","GAP"}', '-', 'Modello indiretto con Tir_modifica remunerazione noleggiatore', 'Media', 'Done', 'AWP-2443', 'Jira', 'BU', 'Nello, Manuela Graziani', 'SAPECC+ADI', 'Sviluppo GAP concluso e condiviso con TIBCO  in data 31/3
- SAP consegnato 17/4
Live dal 18/05', NULL, '2026-04-24', '2026-05-18', '2026-05-18', NULL, '2026 Q2', false, NULL, '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-169', 'AWP', '{"DWH","GAP"}', 'Forfait tombale gestore su flusso DWH (LVR)', '-', 'Media', 'Done', 'AWP-2743', 'Jira', 'IT', 'Lorenzo Bontempi, Manuela Graziani', 'IT', NULL, 'Applicare modifica concordata', '2026-05-15', '2026-05-20', '2026-05-20', NULL, '2026 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-170', 'AWP', '{"Cruscotto AWP","DB"}', 'Contratto schede_Lvr', 'Replicare il modello Gamenet Like anche per la piattaforma LVR. Il modello prevede la richiesta, da parte del gestore, di NOE a lui intestati su schede acquistate da Lottomatica.', 'Media', 'Done', 'AWP-2795', 'Jira', 'IT', 'Manuela Graziani', 'IT', 'Test interno in produzione effettuato con successo', 'verificare gestione da interfaccia + identificazione macchine interessate per ultime veirfiche in produzione con il Business', '2026-06-22', '2026-06-30', NULL, NULL, '2026 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-171', 'AWP', '{"DWH"}', 'Creazione vista/tabella DWH per logica classificazione TIR – Progetto Smart AWP', 'Revisione alla logica di visualizzazione', 'Media', 'Done', 'REP-574', 'Jira', 'BU', NULL, 'IT', NULL, 'Incontro interno per analisi requisito
Sviluppi completati. Predisposizione al collaudo.', '2026-06-05', '2026-06-18', NULL, NULL, '2026 Q2', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-172', 'CROSS', NULL, 'MGM - Storico pratiche Run My Process per LVR', 'Funzione di consultazione delle pratiche importate da RMP', 'Media', 'Done', 'OT-438', 'Jira', 'IT', 'Lorenzo Bontempi', 'GM-DEV', 'In corso aggiornamento piano complessivo che contempla sia i rilasci Kofax sia la chiusura di RMP (che comunque sarà successiva al rilascio dei processi minimi richiesti), con task dedicato alle pratiche da chiudere /  migrare ed archiviare definitivamente', 'test di caricamento file e collaudo', '2025-11-30', NULL, '2025-11-30', '2025-11-30', '2025 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-173', 'CROSS', NULL, 'Adeguamento LGP a CMS Gaming e Report lettura contenuti', '-', 'Media', 'Done', 'OT-928', 'Jira', 'IT', 'Lorenzo Bontempi', 'GM-DEV', 'nuova', 'ricollocazione contenuti su nuova struttura', '2025-09-30', '2025-04-18', '2025-04-28', '2025-04-28', '2025 Q2', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-174', 'CROSS', NULL, 'LGP - introduzione Profilo "Esercizio"', 'VLT-LVR ', 'Media', 'Done', 'OT-850', 'Jira', 'BU', 'Lorenzo Bontempi', 'GM-DEV + ADI', 'concluso in data 10/02', NULL, '2025-03-31', '2025-02-10', '2025-02-10', '2025-02-10', '2025 Q1', false, NULL, '11-20', '6-15') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-175', 'CROSS', NULL, 'MGM - Nuovo CMS', 'Creazione interfacce gestione news e videoguide', 'Media', 'Done', 'OT-920', 'Jira', 'IT', 'Lorenzo Bontempi', 'GM-DEV', 'Live', 'In attesa abilitazione agli utenti', '2025-09-30', '2025-04-07', '2025-04-07', '2025-04-07', '2025 Q2', false, NULL, '21-60', '31-50') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-176', 'CROSS', NULL, 'Passaggio C.I. su GitLab + ripresa Swagger documentazione', '-', 'Media', 'Done', 'OT-533', 'Jira', 'IT', NULL, NULL, 'Live
da UAT a Last-Done', NULL, '2024-09-05', NULL, '2024-09-05', '2024-09-05', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-177', 'CROSS', NULL, 'Recupero numero telefono e peo/pec legata ai pdv', '-', 'Media', 'Done', 'AWP-1311', 'Jira', 'IT', NULL, '-', 'Rilasciato', '-', '2024-09-06', NULL, '2024-09-06', '2024-09-06', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-178', 'CROSS', NULL, 'Visita Ispettiva Straordinaria dei controlli concessori GMNT e LVR', '-', 'Media', 'Done', 'AWP-1282', 'Jira', 'IT', NULL, 'BU', 'Live
da dev a last done', '-', '2024-07-30', NULL, '2024-07-30', '2024-07-30', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-179', 'CROSS', NULL, 'GAP - Dati conto Giudiziale', '-', 'Media', 'Done', 'OT-394', 'Jira', 'IT', NULL, 'IT', 'Live', '-', '2024-05-13', NULL, '2024-05-13', '2024-05-13', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-180', 'CROSS', NULL, 'MGM - Crea User Esercente LGP', '-', 'Media', 'Done', 'OT-435', 'Jira', 'IT', NULL, 'GM-Dev', 'Live il giorno 04/04', NULL, '2024-04-04', NULL, '2024-04-04', '2024-04-04', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-181', 'CROSS', NULL, 'MGM - Crea User Agesoft LGP', '-', 'Media', 'Done', 'OT-437', 'Jira', 'IT', NULL, 'GM-Dev', 'Live il giorno 04/04', NULL, '2024-04-05', NULL, '2024-04-05', '2024-04-05', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-182', 'CROSS', NULL, 'LGP', 'Gestione Utenze (Esterni) - Aggiunta Funzione di presa visione lista utenze', 'Media', 'Done', 'OT-402', 'Jira', 'IT', NULL, 'GM-Dev', 'Individuata soluzione per la validazione lato cliente della propria lista utenze
Live il 22/03', NULL, '2024-03-22', NULL, '2024-03-22', '2024-03-22', '2024 Q1', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-183', 'CROSS', NULL, 'LGP - Adeguamento processo di creazione utenze', 'Modifica per consentire alla sola utenza master di creare le utenze figlie', 'Media', 'Done', 'OT-494', 'Jira', 'IT', NULL, 'GM-Dev', 'Live', NULL, '2024-05-08', NULL, '2024-05-08', '2024-05-08', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-184', 'CROSS', NULL, 'MGM - Console controllo LGP', 'Modifica utenze', 'Media', 'Done', 'OT-390', 'Jira', 'IT', NULL, 'GM-Dev', 'Live il giorno 04/04', NULL, '2024-04-04', NULL, '2024-04-04', '2024-04-04', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-185', 'CROSS', NULL, 'MGM', 'Porting gestione profili (amm.interna) ed elenco funzione di LGP su MGM', 'Media', 'Done', 'OT-482', 'Jira', 'IT', NULL, 'GM-Dev', 'Live', NULL, '2024-05-08', NULL, '2024-05-08', '2024-05-08', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-186', 'CROSS', NULL, 'MGM', 'Creazione interfacce gestione contenuti statici, caricamento file e tipologiche per CMS', 'Media', 'Done', 'OT-675', 'Jira', 'IT', NULL, '-', 'live', '-', '2024-10-16', NULL, '2024-10-16', '2024-10-16', '2024 Q4', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-187', 'CROSS', NULL, 'LGP - lavorazione CMS per banner, pagine, contatti', 'Prima fase di migrazione verso nuovo cms', 'Media', 'Done', 'OT-483', 'Jira', 'IT', NULL, 'GM-Dev', 'Live', NULL, '2024-09-10', NULL, '2024-09-10', '2024-09-10', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-188', 'CROSS', '{"DWH"}', 'DWH', 'Richiesta inserimento misura macroaree su modelli AWP e VLT', 'Media', 'To Be Planned', 'REP-630', 'Jira', 'IT', NULL, NULL, NULL, NULL, '2026-07-31', NULL, NULL, NULL, '2026 Q3', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-189', 'CROSS', NULL, 'SEGAG - Modello power BI', 'sanatoria dei dati che giungono su DWH nel campo "Tipologia sede albo"', 'Media', 'Done', 'AWP-1305', 'Jira', 'IT', NULL, '-', 'Live', NULL, '2024-09-24', NULL, '2024-09-24', '2024-09-24', '2024 Q3', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-190', 'CROSS', NULL, 'Predisposizione DB e FS per CMS', '-', 'Media', 'Done', 'OT-471', 'Jira', 'IT', NULL, ' GM-Dev', 'Completata il giorno 11/04 (da mantenere fino a prox avanzamento interno)', NULL, '2024-04-11', NULL, '2024-04-11', '2024-04-11', '2024 Q2', false, NULL, NULL, NULL) on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-191', 'VLT', '{"Se-Gag"}', 'Automatizzazione Anagrafica DB Sale/Manutentori VLT', '-', 'Media', 'Done', 'VLT-310', 'Jira', 'BU', 'Manuela Graziani', 'Demand/IT', 'Attualizzati dati da A. Centaro per caricamento del T0,
Predisposizione delle tabelle parallele per monitoraggio nuovi dati pre switch SAP', 'Rilascio in Prod da concordare. Mandato action plan il 9/4.', '2025-04-18', '2026-04-21', '2026-04-21', '2026-04-21', '2026 Q2', false, 'Impianto modificato per coprire anche la casistica di codici errore specifici inizialmente OoS', '21-60', '16-30') on conflict (id_progetto) do nothing;
insert into progetti (id_progetto, area, prodotto, macro_attivita, descrizione, priorita, stato, jira_code, fonte, owner_progetto, referenti, action_owner, last_action, to_do, due_date, due_date_ripianificata, deadline_chiusura, go_live_date, quarter_pianificato, critico_per_business, note, effort, effort_storico) values ('MIG-192', 'VLT', NULL, 'MGM - Aggiunta Sala Kofax', '-', 'Media', 'Done', 'VLT-527', 'Jira', 'IT', 'Lorenzo Bontempi, Manuela Graziani', 'IT', 'nuova', 'da mandare in prod post freeze rilasci (7/1)', '2025-12-31', '2026-01-08', '2026-01-08', '2026-01-08', '2026 Q1', false, NULL, '0-5', '0-5') on conflict (id_progetto) do nothing;
